### ISSUE TITLE
Release 10 seems to break on prisma 2.18 Release 9 does not

### ISSUE THREAD

**Issue by doflo-dfa** [unlight/prisma-nestjs-graphql#10]
This builds in @9 and emits a full set of files, it takes about 4 minutes

In @10 it takes over 10 minutes and emits empty files for a number of the models

<details>
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Tracker {
  id                 String            @id @default(cuid())
  name               String
  createdAt          DateTime          @default(now())
  updatedAt          DateTime          @updatedAt
  trackingId         String            @unique
  team               Team              @relation(fields: [teamId], references: [id])
  type               TrackerType       @default(JSAdHoc)
  connector          BridgeAppPointer? @relation(fields: [bridgeAppPointerId], references: [id])
  metadata           Json?
  teamId             String
  bridgeAppPointerId String?
}

enum TrackerType {
  JSAdHoc
  JSRelated
}

model BridgeApp {
  id               String             @id @default(cuid())
  createdAt        DateTime           @default(now())
  updatedAt        DateTime           @updatedAt
  BridgeAppPointer BridgeAppPointer[]
}

model Project {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name      String
  lowerName String

  flows Flow[]

  UIs UI[]

  // This should be a vector image from our library or an SVG upload
  logo String?

  // Owner of this project
  team   Team   @relation(fields: [teamId], references: [id])
  teamId String

  pending Boolean @default(true)

  @@unique([lowerName, teamId])
}

model UI {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name      String
  lowerName String

  logo String?

  project   Project @relation(fields: [projectId], references: [id])
  projectId String

  data Json

}

model Flow {

  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name      String
  lowerName String

  logo String?

  owner  User   @relation(fields: [userId], references: [id])
  userId String

  project   Project @relation(fields: [projectId], references: [id])
  projectId String

  elements Element[]

  connections Connection[]

}

model Connection {

  id String @id @default(cuid())

  createdAt DateTime @default(now())

  updatedAt DateTime @updatedAt

  source   Element @relation(fields: [sourceId], references: [id], name: "sourceConnection")
  sourceId String

  target   Element @relation(fields: [targetId], references: [id], name: "targetConnection")
  targetId String

  flow   Flow   @relation(fields: [flowId], references: [id])
  flowId String

  Element   Element? @relation(fields: [elementId], references: [id])
  elementId String?
}

enum ProfileVisibility {
  // The profile is indexed and visible
  Indexable
  // The profile is visible but has a no-robots header
  Visibile
  // The profile is not linked on the website but is reachable
  Hidden
  // The profile is visible only to members of doFlo and your team
  Blocked
}

model DeveloperProgram {
  id                String            @id @default(uuid())
  createdAt         DateTime          @default(now())
  updatedAt         DateTime          @updatedAt
  name              String
  logo              String?
  bio               String?
  slug              TokenUsage?       @relation(fields: [tokenUsageUsageId], references: [usageId])
  visibility        ProfileVisibility @default(Indexable)
  BuildConnector    BuildConnector[]
  Team              Team[]            @relation("developerProgram")
  tokenUsageUsageId String?
}

enum HostType {
  GitHub
  GitLab
  AzureCI
  BitBucket
}

// This is essentially source control repo provider ie. github, gitlab, azure pipelines
model BuildConnector {
  appId       Int
  installId   Int
  createdAt   DateTime          @default(now())
  updatedAt   DateTime          @updatedAt
  type        HostType          @default(GitHub)
  devProgram  DeveloperProgram? @relation(fields: [developerProgramId], references: [id])
  account     String?
  accountName String?
  accountType String?
  logo        String?
  repos       Repo[]

  @@id([appId, installId])
  developerProgramId String?
}

model Repo {
  // full repo name
  id                      String          @id
  ext_id                  String?
  createdAt               DateTime        @default(now())
  updatedAt               DateTime        @updatedAt
  namespace               Namespace?      @relation(fields: [namespaceId], references: [id])
  actions                 BuildAction[]
  BuildConnector          BuildConnector? @relation(fields: [buildConnectorAppId, buildConnectorInstallId], references: [appId, installId])
  buildConnectorAppId     Int?
  buildConnectorInstallId Int?
  namespaceId             String?
}

enum BuildStatus {

  // Initial Status
  Starting

  Building

  Publishing

  // Build & Publish Completed Status - end of live life cycle = good
  Completed

  // Optimization step where we dump the pulsar log to S3 and future
  CompressingLog

  // Build & Publish Completed Status - end of live life cycle = bad
  Failed

}

model BuildAction {
  df_sha        String      @id @default(cuid())
  createdAt     DateTime    @default(now())
  updatedAt     DateTime    @updatedAt
  status        BuildStatus
  output        BuildOutput @relation(fields: [buildOutputId], references: [id])
  Repo          Repo?       @relation(fields: [repoId], references: [id])
  repoId        String?
  buildOutputId String
}

model BuildOutput {
  id          String            @id @default(cuid())
  annotations BuildAnnotation[]
  title       String?
  summary     String?
  BuildAction BuildAction[]
}

model BuildAnnotation {
  id            String       @id @default(cuid())
  title         String?
  summary       String?
  lineNumber    Int?
  colStart      Int?
  colEnd        Int?
  BuildOutput   BuildOutput? @relation(fields: [buildOutputId], references: [id])
  buildOutputId String?
}

model PartnerProgram {
  id                String            @id @default(uuid())
  createdAt         DateTime          @default(now())
  updatedAt         DateTime          @updatedAt
  name              String
  logo              String?
  bio               String?
  slug              TokenUsage?       @relation(fields: [tokenUsageUsageId], references: [usageId])
  visibility        ProfileVisibility @default(Indexable)
  Team              Team[]            @relation("partnerProgram")
  tokenUsageUsageId String?
}

model AffiliateProgram {
  id                String            @id @default(uuid())
  createdAt         DateTime          @default(now())
  updatedAt         DateTime          @updatedAt
  name              String
  logo              String?
  bio               String?
  slug              TokenUsage?       @relation(fields: [tokenUsageUsageId], references: [usageId])
  visibility        ProfileVisibility @default(Indexable)
  Team              Team[]            @relation("affiliateProgram")
  tokenUsageUsageId String?
}

enum FlowSharingScheme {
  // Only owners can see new flows
  OwnersOnly
  // Team can view
  View
  // Team can invoke
  Invoke
  // Team can edit
  Edit
}

enum ProjectSharingScheme {
  // Only owners can see new projects
  OwnersOnly
  // Team can view new project
  TeamVisible
}

model Team {
  id        String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
  logo      String?

  /// This maping does not include role information
  users User[] @relation("teamMembership")

  /// This is the key for the developer program
  developerProgram DeveloperProgram? @relation("developerProgram", fields: [developerProgramId], references: [id])

  /// This is the key for the partner program
  partnerProgram PartnerProgram? @relation("partnerProgram", fields: [partnerProgramId], references: [id])

  /// This is the key for the affiliate program
  affiliateProgram AffiliateProgram? @relation("affiliateProgram", fields: [affiliateProgramId], references: [id])

  teamSize String?

  flowSharingScheme FlowSharingScheme? @default(value: OwnersOnly)

  projectSharingScheme ProjectSharingScheme? @default(value: OwnersOnly)

  /// Credentials owned by this team
  credentials Credential[]

  projects  Project[]
  lastUsers User[]    @relation("lastTeamId")

  /// Tokens Owned Directly by this team
  Token Token[]

  /// Models Owned by This team ( As Developers )
  /// CredentialModel CredentialModel[]

  /// Trackers Owned by This team ( As Users )
  Trackers Tracker[]

  /// Namespaces Owned by This team ( As Developers )
  Namespaces         Namespace[]
  CredentialModel    CredentialModel[]
  developerProgramId String?
  partnerProgramId   String?
  affiliateProgramId String?
}

model User {
  id        String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  username String @unique

  /// Profile email address of the user
  email String?

  /// Full name of the user
  name String?

  /// Last team the user selected in the UI
  lastTeam Team? @relation(name: "lastTeamId", fields: [lastTeamId], references: [id])

  lastTeamId String?

  role String?

  /// Profile picture URL
  picture String?

  /// Profile picture URL
  remotePicture String?

  credentials Credential[]

  flows Flow[]

  teams Team[] @relation("teamMembership")

}

/// Root Element Type (Workers / Signals)
model Element {

  id          String           @id @default(cuid())
  createdAt   DateTime         @default(now())
  updatedAt   DateTime         @updatedAt
  credentials ElementPointer[]

  targets Connection[] @relation("sourceConnection")

  sources Connection[] @relation("targetConnection")

  Flow   Flow?   @relation(fields: [flowId], references: [id])
  flowId String?

  Connection Connection[]
}

// /// Instance of a credential
model Credential {

  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  /// Credential Model
  type    CredentialModel? @relation(fields: [modelId], references: [id])
  modelId String?

  data Json?

  user   User?   @relation(fields: [userId], references: [id])
  userId String?

  team   Team?   @relation(fields: [teamId], references: [id])
  teamId String?

  ElementModel     ElementModel?      @relation(fields: [elementModelId], references: [id])
  elementModelId   String?
  ElementPointer   ElementPointer[]
  BridgeAppPointer BridgeAppPointer[]
}

enum ResourceType {

  DeveloperSlug

  PartnerSlug

  AffiliateSlug

  Namespace

}

model TokenUsage {

  usageId String @id @default(cuid())

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  token      Token  @relation(name: "primaryToken", fields: [token_slug], references: [token])
  token_slug String

  nextToken       Token?  @relation(name: "nextToken", fields: [next_token_slug], references: [token])
  next_token_slug String?

  usage ResourceType

  DeveloperProgram DeveloperProgram[]
  PartnerProgram   PartnerProgram[]
  AffiliateProgram AffiliateProgram[]
  Namespace        Namespace[]
}

model Namespace {

  id String @id @default(uuid())

  key TokenUsage? @relation(fields: [tokenUsageUsageId], references: [usageId])

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  name        String
  description String?

  logo String?

  credentials CredentialModel[] @relation(name: "credentialKey")

  elements ElementModel[] @relation(name: "elementKey")

  bridgeApps BridgeAppModel[] @relation(name: "bridgeAppKey")

  owner Team @relation(fields: [teamId], references: [id])

  Repo              Repo[]
  tokenUsageUsageId String?
  teamId            String
}

model Token {
  token String @id

  createdAt DateTime @default(now())

  updatedAt DateTime @updatedAt

  owner Team @relation(fields: [ownerId], references: [id])

  ownerId String

  usages TokenUsage[] @relation(name: "primaryToken")

  nextUsages TokenUsage[] @relation(name: "nextToken")

}

model BridgeAppModel {
  id String @id @default(cuid())

  displayName String
  logo        String?

  /// DFRN:[namespace]/bridgeapp/[name]/latest/:[instance]
  /// DFRN:[namespace]/bridgeapp/[name]/[semVer]/:[instance]?ch=stage - instance as tranlated via specific model version
  /// DFRN:[namespace]/bridgeapp/[name]/[semVer]/:[instance]?ch=dev-00000000-0000-0000-0000-000000000000 == unique dev channel
  /// DFRN:[namespace]/bridgeapp/[name]/[semVer]/:[instance] == prod
  /// DFRN:[namespace]/bridgeapp/[name]/[semVer]/
  key   Namespace @relation(name: "bridgeAppKey", fields: [keyId], references: [id])
  keyId String

  name String

  major Int @default(0)
  minor Int @default(0)
  patch Int @default(1)

  /// Primary chanes are Prod, Stage, Adhoc Dev-{branch} are supported for message routing back to the developer
  channel String

  /// This is the key to the URL as well as Contentful for the purposes of help docs - this is almost always the same as the key and thus can be left blank
  // docsKey  TokenUsage? @relation(name: "bridgeAppDocKey", fields: [docKeyId], references: [usageId])
  // docKeyId String?

  /// This is the #hash target with in potentially larger documentation setups
  docTarget String?
  /// This is the key to the URL as well as Contentful for the purposes of help docs
  // docsKey  Token?  @relation(name: "bridgeAppDocKey", fields: [docKeyId], references: [token])
  // docKeyId String?

  /// This is the #hash target with in potentially larger documentation setups
  /// docTarget String?

  /// Global credential instances associated to elements of this model type
  /// credentialInstances Credential[]

  /// Available credential types for this element type
  /// credentials ModelPointer[]

  /// Instances of this type
  /// instances BridgeAppPointer[]

  /// BridgeAppModelPointer BridgeAppModelPointer[]
  BridgeAppModelPointer BridgeAppModelPointer[]
  BridgeAppPointer      BridgeAppPointer[]
}

model ElementModel {

  id String @id @default(cuid())

  displayName String
  logo        String?

  key   Namespace @relation(name: "elementKey", fields: [keyId], references: [id])
  keyId String

  major Int @default(0)
  minor Int @default(0)
  patch Int @default(1)

  /// Primary chanes are Prod, Stage, Adhoc Dev-{branch} are supported for message routing back to the developer
  channel String

  /// This is the key to the URL as well as Contentful for the purposes of help docs
  // docsKey  TokenUsage? @relation(name: "elementDocKey", fields: [docKeyId], references: [usageId])
  // docKeyId String?

  /// This is the #hash target with in potentially larger documentation setups
  docTarget String?

  /// Global credential instances associated to elements of this model type
  credentialInstances Credential[]

  /// Available credential types for this element type
  credentials ModelPointer[]

  /// Instances of this type
  instances ElementPointer[]

}

model ModelPointer {

  id String @id @default(cuid())

  credentialModel   CredentialModel? @relation(fields: [credentialModelId], references: [id])
  credentialModelId String?

  elementModel   ElementModel? @relation(fields: [elementModelId], references: [id])
  elementModelId String?

  required Boolean @default(false)

}

model BridgeAppModelPointer {

  id String @id @default(cuid())

  credentialModel   CredentialModel? @relation(fields: [credentialModelId], references: [id])
  credentialModelId String?

  bridgeAppModel   BridgeAppModel? @relation(fields: [bridgeAppModelId], references: [id])
  bridgeAppModelId String?

}

model ElementPointer {

  id String @id @default(cuid())

  credential   Credential? @relation(fields: [credentialId], references: [id])
  credentialId String?

  element   Element? @relation(fields: [elementId], references: [id])
  elementId String?

  ElementModel   ElementModel? @relation(fields: [elementModelId], references: [id])
  elementModelId String?

  selected Boolean @default(false)

}

model BridgeAppPointer {
  id String @id @default(cuid())

  credential   Credential? @relation(fields: [credentialId], references: [id])
  credentialId String?

  bridgeApp   BridgeApp? @relation(fields: [bridgeAppId], references: [id])
  bridgeAppId String?

  bridgeAppModel   BridgeAppModel? @relation(fields: [bridgeAppModelId], references: [id])
  bridgeAppModelId String?
  Tracker          Tracker[]
}

///  Model of a credential
model CredentialModel {

  id String @id @default(cuid())

  /// Is this credential visible in the UI
  hidden Boolean

  /// this is the default active credential in its channel, there can be only one per channel
  latest Boolean?

  /// This value is very rarely used, (in the back end admin and status pages... at least so far)
  displayName String

  /// URL that points to cloudinary
  logo String?

  /// DFRN:[token]/credentials/[name]/latest/:[instance]
  /// DFRN:[token]/credentials/[name]/[semVer]/:[instance]?ch=stage - instance as tranlated via specific model version
  /// DFRN:[token]/credentials/[name]/[semVer]/:[instance]?ch=dev-00000000-0000-0000-0000-000000000000 == unique dev channel
  /// DFRN:[token]/credentials/[name]/[semVer]/:[instance] == prod
  /// DFRN:[token]/credentials/[name]/[semVer]/
  key   Namespace @relation(name: "credentialKey", fields: [keyId], references: [id])
  keyId String

  name String

  major Int @default(0)
  minor Int @default(0)
  patch Int @default(1)

  /// Primary chanes are Prod, Stage, Adhoc Dev-{branch} are supported for message routing back to the developer
  channel String

  /// This is the key to the URL as well as Contentful for the purposes of help docs - this is almost always the same as the key and thus can be left blank
  // docsKey  TokenUsage? @relation(name: "credentialDocKey", fields: [docKeyId], references: [usageId])
  // docKeyId String?

  /// This is the #hash target with in potentially larger documentation setups
  docTarget String?

  precedents  CredentialModel[] @relation(name: "precedents", references: [id])
  descendants CredentialModel[] @relation(name: "precedents", references: [id])

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  ownerTeam   Team   @relation(fields: [ownerTeamId], references: [id])
  ownerTeamId String

  /// Model of the credential
  model Json

  /// Available Elements
  elements ModelPointer[]

  /// Available Bridge Apps
  bridgeApps BridgeAppModelPointer[]

  /// Derived Credentials
  credentials Credential[]

  @@unique([keyId, name, channel, major, minor, patch])
  @@unique([keyId, name, channel, latest])
}
</details>

**Comment by unlight** [comment]
@doflo-dfa 

Thanks for report, I found the issue.
There is an conflict with model names and internal generated prisma names (ending with `Output`).

Will be fixed.

**Comment by doflo-dfa** [comment]
Sorry I keep finding the fun errors.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
