### ISSUE TITLE
How to enter Date type data

### ISSUE THREAD

**Issue by fuergaosi233** [unlight/prisma-nestjs-graphql#100]
<img width="918" alt="image" src="https://user-images.githubusercontent.com/22197568/163464591-af833648-0e10-40e1-8b07-7175ee48d167.png">
This is my Schema , I use the **DateTimeFilter** provided by **prisma-nestjs-graphql**, it shows that there is a scalar of Date, but I don't know what form it should be transferred in, I have tried **"2022-04-14T03:57:05.118Z"** and **"2022-02-15 04:53:33"**, but they are null.

**Comment by unlight** [comment]
According to nestjs docs
2022-04-14T03:57:05.118Z is valid format

**Comment by unlight** [comment]
Source code https://github.com/nestjs/graphql/blob/master/packages/graphql/lib/scalars/iso-date.scalar.ts

serialize produce null, looks like you need convert date property of your result object from prisma to  Date instance.

**Comment by fuergaosi233** [comment]
> unlight

not return null, is the input data becomes a null value.
<img width="458" alt="image" src="https://user-images.githubusercontent.com/22197568/163586516-b0bd3ec3-5fc2-44dc-89cd-29931ef38e61.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/22197568/163586537-a7683826-7c04-4da6-a3d4-49d176b69f2f.png">

**Comment by unlight** [comment]
DateTimeFilter is used for querying data, not for creating.

I've made a test, and there is no issues with creating date.
```ts
    @Mutation(() => Dummy)
    createDummy(@Args('data') create: DummyCreateInput) {
        console.log('create', create);
        const dummy = new Dummy();

        dummy.created = new Date();

        return dummy;
    }
```


![image](https://user-images.githubusercontent.com/301732/163603754-58928968-1d60-4570-aab7-19c3ec5a343a.png)

**Comment by fuergaosi233** [comment]
I can't reproduce this, I think maybe there are other dates in my environment that are overwritten

**Comment by fuergaosi233** [comment]
I found out why, I had previously defined the type of Date 😅. Thanks for your work.
