### ISSUE TITLE
Composite @@id field not generated in model

### ISSUE THREAD

**Issue by hbriese** [unlight/prisma-nestjs-graphql#108]
The composite @@id field is not generated in the model.

### Example schema
```
model User {
  firstName String
  lastName  String

  @@id([firstName, lastName])
}
```

### Object model
```
@ObjectType()
export class Contact {

    @Field(() => String, {nullable:false})
    firstName!: string;

    @Field(() => String, {nullable:false})
    lastName!: string;

    // EXPECTED: id field is present
    // @Field(() => String, {nullable:false})
    // id!: string;
}
```

Is this issue similar to #86 in that Prisma needs to be patched?
The id field **is** generated as expected in `FindUnqiue...` object

**Comment by unlight** [comment]
I do not think that #86 is related.
And absence of `id` looks correct for me. `id` is a reference for primary key.

```ts

@InputType()
export class ContactWhereUniqueInput {

    @Field(() => ContactFirstNameLastNameCompoundUniqueInput, {nullable:true})
    firstName_lastName?: ContactFirstNameLastNameCompoundUniqueInput;
}

@InputType()
export class ContactWhereUniqueInput {

    @Field(() => ContactFirstNameLastNameCompoundUniqueInput, {nullable:true})
    firstName_lastName?: ContactFirstNameLastNameCompoundUniqueInput;
}

@InputType()
export class ContactFirstNameLastNameCompoundUniqueInput {

    @Field(() => String, {nullable:false})
    firstName!: string;

    @Field(() => String, {nullable:false})
    lastName!: string;
}

```

**Comment by hbriese** [comment]
Sorry I think I misunderstood the mechanism behind the composed IDs so this is not a bug as you have pointed out.

This ticket came about when I got an error from Apollo cache - due to the fact that the returned object didn't have an ID. The only way to solve this without writing custom merging logic on the client-side was to replace my composed ID with an explicit ID in order to get the ID field back.
Do you have any suggestions?

**Comment by unlight** [comment]
I do not know how Apollo cache works. But there is a feature NestJS like computed field - decorator   `@ResolveField` see nestjs docs. You can concat or create hash from first and last name.

I did not check it. This is what I can say from the top of my head.
