### ISSUE TITLE
Question: Which versioning system do you use?

### ISSUE THREAD

**Issue by felinto-dev** [unlight/prisma-nestjs-graphql#11]
Hi!

Thank you for doing a great job, but I would like to ask if you are aware of the SEMVER specification. I saw the version history of the package and there are many MAJOR versions every 2 weeks - 1 month, and that worries me a little.

Do you follow any specifications to define versioning? Thanks.

**Comment by unlight** [comment]
Hi. Yes, I'm aware of SEMVER and I'm follow it.
But prisma does not, and may have breaking changes between minor versions.

For example, prisma-nestjs-graphql v8 will work prisma v2.15, but will not work with prisma v2.16.

Some other recent breaking changes were introduced because changing defaults of configs and removing some unstable features.

**Comment by felinto-dev** [comment]
```
Why does Prisma not follow SemVer?
Prisma is one of many developer tools that doesn't follow the SemVer specification. The main reason is that Prisma has a huge developer surface made up by several tools (the Prisma CLI, Prisma Client, Prisma Migrate, Prisma Studio, ...). Therefore, a breaking change in one tool might not affect usage of another tool, so incrementing the major version number for the tools that are not affected might not be justified.
```

https://www.prisma.io/docs/about/releases

Thanks.

**Comment by rodrigooler** [comment]
@unlight makes sense, is doing a great job!

**Comment by rodrigooler** [comment]
> Hi. Yes, I'm aware of SEMVER and I'm follow it.
> But prisma does not, and may have breaking changes between minor versions.
> 
> For example, generator prisma-nestjs-graphql v8 will work prisma v2.15, but will not work with prisma v2.16.
> So need new major version just to adapt to new prisma minor version.
> 
> Some other recent breaking changes were introduced because changing defaults of configuration and removing some unstable features.

@unlight makes sense, is doing a great job!
