### ISSUE TITLE
Question: computed properties and other non-prisma properties

### ISSUE THREAD

**Issue by jasonmacdonald** [unlight/prisma-nestjs-graphql#116]
I'm sure this is possible but I'm struggling to understand exactly how I can augment a generated model with additional properties that don't exist in the database schema. One simple example would be on a `User` object adding a property called `fullname` which simply computes the value from `firstname` and `lastname`. 

_I don't want to do this specifically, it was just the simplest example I could think of._

I understand I could simply extend the base generated model and add it there, but this doesn't allow the property to be returned if someone retrieves the model as part of a nested query, at least not without adding a `FieldResolver` to every `Resolver` in the system that might be able to return a nested select. Ideally I would like to just have the extra properties on the generated Object, regardless of where it is called, but not have it try to save those properties to the DB, I hope that makes sense.

So, I guess the question is, is there any way to add properties to the generated Object model that are not directly related to a column in the Prisma model?

Thanks!

**Comment by unlight** [comment]
Adding `FieldResolver` is the right way to add computed fields.
Of course it's possible to add `@Field()` decorator to property, e.g. `fullName()` of User object, but how you will load additional data, which almost always async? And how get access to other objects (except globals)? I think it's wrong way.

**Comment by jasonmacdonald** [comment]
> Adding `FieldResolver` is the right way to add computed fields. 


I was afraid of that :) 

As I said, it wasn't really the computed property I was looking for, it was just a simpler example than trying to explain what I was trying to do. I was hoping there might have been a way to add a property that just called out to another service, but could be hidden from input and only added to the output Object. In the end, I suppose I'll have to go the resolver route. 

I figured it was worth a shot in asking if perhaps there was something else. Thanks!
