### ISSUE TITLE
[ERROR] MySQL BigInt generates a String

### ISSUE THREAD

**Issue by JoseAndresMejiasRojas** [unlight/prisma-nestjs-graphql#119]
Let's say we have this schema:

```
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

generator nestgraphql {
  provider = "node node_modules/prisma-nestjs-graphql"
  output   = "generated"
  reExport = Single
}

model EntityTest {
  id         String @id @map("Id")
  columnTest BigInt @map("ColumnTest") @db.BigInt

  @@map("Test")
}
```

With my current version, I get the following ObjectType:

 ```
@ObjectType()
export class EntityTest {
  @Field(() => ID, { nullable: false })
  id!: string;

  @Field(() => String, { nullable: false })
  columnTest!: bigint;
}
```

As you can see, the columnTest attribute has an error. The "JavaScript type" (bigint) is correct. However, the "@Field type" (String) type is a string, which is wrong.

Environment:
```
"@prisma/client": "3.14.0",
"prisma": "3.14.0",
"prisma-nestjs-graphql": "16.0.1",
```

**Comment by unlight** [comment]
BigInt is non builtint graphql scalar. All non standard scalars will be typed as string.
See https://github.com/unlight/prisma-nestjs-graphql#graphqlscalars

I think ts property as bigint is not valid also. It should also string, unless custom graphql field decorator applied.
