### ISSUE TITLE
Model types bing created don't reflect optional fields

### ISSUE THREAD

**Issue by dieeisenefaust** [unlight/prisma-nestjs-graphql#120]
When the primary model TS type is created, fields are not correctly marked as optional based on what is written in schema.prisma.

Is there a reason for this?

This can be seen in the example code provided in this repo.

User model in schema.prisma:
![image](https://user-images.githubusercontent.com/5838917/172942715-8e70b1c0-7196-4159-8bc8-b1cc44643186.png)

user.model.ts (notice that bio, image, countComments, rating, money, role all show are required):
![image](https://user-images.githubusercontent.com/5838917/172943848-d9ad7c30-985c-4772-a51e-b330a06c2c88.png)

**Comment by unlight** [comment]
Scalar fields in model does not become optional `?`
instead it the type will be `T | null`

Reason: Compatibity with prisma types

Optional fields in prisma schema become nullable columns, null value from database of such kind of field will be mapped to null javascript, and cannot be undefined.
