### ISSUE TITLE
Args has Missing fields i.e `UserCreateArgs` not equivalent to `CreateOneUserArgs`

### ISSUE THREAD

**Issue by marmik18** [unlight/prisma-nestjs-graphql#129]
Hi,
I am not sure that whether I am missing something or the fields are actually not present.

For reference If I have a prisma model:
```ts
model Model{
  id          String        @id
  firstName   String
  lastName    String
}
```

I have generated type with the following generator configuration

```ts
generator nestgraphql {
  provider         = "prisma-nestjs-graphql"
  tsConfigFilePath = "tsconfig.json"
  purgeOutput      = true
  reExport         = Directories
}
```
The following types are generated under `CreateOneUserArgs` :
```ts
@ArgsType()
export class CreateOneUserArgs {

    @Field(() => UserCreateInput, {nullable:false})
    @Type(() => UserCreateInput)
    data!: UserCreateInput;
}
```
But prisma has 2 more fields `select` and `include` for `UserCreateArgs`:
```ts
  export type UserCreateArgs = {
    select?: UserSelect | null
    include?: UserInclude | null
    data: XOR<UserCreateInput, UserUncheckedCreateInput>
  }
 ```
What do I need to do if I want to pass select and include fields as well? 

Thank you for taking the time to read this :)

**Comment by unlight** [comment]
`include` and `select` as parameters has no much sense in GraphQL world.
Please read discussion in similar issues #112 #50

**Comment by marmik18** [comment]
I understand that it does not make much sense. But in my case I want to keep the types as a single source of truth and I have created a private package in which all the types and prisma calls are just wrapped (for future flexibility). I import these in my services and in my business logic as I need them. Do you see any alternative through which I can enable these fields?

**Comment by unlight** [comment]
I got your point. 
But still I think that is the wrong way.

Using same objects with for working with database and for business logic is not scalable (prisma uses plain object, but business logic probably should work with different kind of object: value object  / entity object, domain model, etc.)
It's common practice to use different classes for transfering between layers (even if they have same interface).

Second, GraphQL input object does not support union types, but prisma does.

**Comment by unlight** [comment]
> Do you see any alternative through which I can enable these fields?

You can generate abstract ojects https://github.com/unlight/prisma-nestjs-graphql#objecttype
and extend them by adding new fields/properties
