### ISSUE TITLE
Prefer use default export

### ISSUE THREAD

**Issue by felinto-dev** [unlight/prisma-nestjs-graphql#13]
Most files have only one constant (variable). Instead of having to do

`import { User } from '@generated/models/user.model.ts'
`
It would not be preferable

`import User from '@generated/models/user.model.ts'
`
What do you think about this?

In this case, when generating the files, it would only be necessary to add a default export.

**Comment by unlight** [comment]
My preference that `export default` is a bad choice over named export (I'm not saying that is bad practice).

- https://basarat.gitbook.io/typescript/main-1/defaultisbad
- https://palantir.github.io/tslint/rules/no-default-export
- https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

I think it can be implemented under option.

**Comment by felinto-dev** [comment]
You changed my mind.
Thanks for the interesting links.

Much appreciated.
