### ISSUE TITLE
How to generate Promise<> with @PropertyType

### ISSUE THREAD

**Issue by lukadriel7** [unlight/prisma-nestjs-graphql#138]
Hello, 
I was wondering how I could type my fields with generics, specifically Promise<FileUpload>.
I want to achieve the following:
```
@InputType()
export class RecipeCreateInput {
  @Field(() => String, { nullable: true })
  id?: string;
  @Field(() => GraphQLJSON, { nullable: false })
  name!: any;
  @Field(() => GraphQLUpload, { nullable: true })
  image?: Promise<FileUpload>;
}
```
I want the image field to be of type Promise<FileUpload>. 
I can do FileUpload only but not Promise.

**Comment by unlight** [comment]
1. Create `type PromiseFileUpload = Promise<FileUpload>`
2. Map it by [paths](https://www.typescriptlang.org/tsconfig#paths) feature of tsconfig (so you can access it from anywhere)
3. Use `@Property()` directive to replace typescript type for desired property

**Comment by lukadriel7** [comment]
Thank you very much
