### ISSUE TITLE
@HideField Imports

### ISSUE THREAD

**Issue by Will-Mann-16** [unlight/prisma-nestjs-graphql#14]
Hi there, I was using the package and used `/// @HideField() ` to hide some of my many-to-many relations on one side of the field, but when I hide the field, on generation the type does not get imported, so I have to manually add them after generate. Any solutions?

**Comment by unlight** [comment]
I will check

**Comment by unlight** [comment]
@Will-Mann-16 
Could you provide more info about this field,
is it scalar or other model, or custom type?

**Comment by Will-Mann-16** [comment]
It's another model here
