### ISSUE TITLE
[BUG] CodeBlockWriter is not a constructor

### ISSUE THREAD

**Issue by yuyake0084** [unlight/prisma-nestjs-graphql#146]
Thanks for providing a great library.
I used this library to deploy with Github Actions all the time, but today I suddenly got the following error.

## Error

```
------                                                                                            
 > [8/9] RUN yarn prisma generate:                                                                
#0 0.395 yarn run v1.22.19                                                                        
#0 0.416 $ /app/node_modules/.bin/prisma generate                                                 
#0 1.019 Environment variables loaded from .env                                                   
#0 1.021 Prisma schema loaded from prisma/schema.prisma
#0 3.960 Error: 
#0 3.960 ✔ Generated Prisma Client (4.3.1 | library) to ./node_modules/@prisma/client in 206ms
#0 3.960 
#0 3.960 CodeBlockWriter is not a constructor
#0 3.960 
#0 3.960 
#0 4.058 error Command failed with exit code 1.
#0 4.059 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
```

There was no particular change in the code, and I didn't get an error in CI for the past two weeks, but it suddenly appeared not only in Github Actions but also in Docker in the local environment.

Any idea what might be causing this issue?

## Version

- Node.js
  - 18.10.0
- Package
  - prisma-nestjs-graphql
    - ^17.0.1
  - prisma
    - ^4.6.1
  - @prisma/client
    - 4.6.1

**Comment by Luferov** [comment]
Same error

**Comment by unlight** [comment]
It is `ts-morph` dependency which is set to `>=11`, ts-morph introduced breaking changes (typescript 4.9) in v 17. Use "override/resolutions" feature of your package manager (pin ts-morph to 16.X.X)

**Comment by Luferov** [comment]
> It is `ts-morph` dependency which is set to `>=11`, ts-morph introduced breaking changes (typescript 4.9) in v 17. Use "override/resolutions" feature of your package manager (pin ts-morph to 16.X.X)

Are you planing update `ts-morph` to 11 version? It would be great!

**Comment by unlight** [comment]
Yes, I'll pin `ts-morph` to specific range `11-16`.
