### ISSUE TITLE
Emit compiled bundle

### ISSUE THREAD

**Issue by unlight** [unlight/prisma-nestjs-graphql#15]
People want have single big file with generated classes instead of multiple.
Similar issues: #6 #12 

Facts:
- ts-morph allows to emit compiled file with declarations
- classes are not hoisted and must be properly sorted to avoid fall into [TDZ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz)
- Unable to maintain it (make manual changes, etc.)

What need to do before:
- <strike>Decouple generation, get rid of dependency of `SourceFile` in different types of handlers</strike>
- <strike>Create helper function to resort classes</strike>
- <strike>Emit dts with errors</strike>

**Comment by unlight** [comment]
Check new options `emitSingle` and `emitCompiled`
https://github.com/unlight/prisma-nestjs-graphql#emitsingle
https://github.com/unlight/prisma-nestjs-graphql#emitcompiled

**Comment by yassinebridi** [comment]
It works like a charm @unlight, the performance too is really good, thank you.

**Comment by yassinebridi** [comment]
@unlight I just tried the `emitSingle` opiton, i think there is a dead zone issue, where for example:
a `UserCreateNestedManyWithoutCityInput` is trying to access `UserWhereUniqueInput`, befor the latter is created.

**Comment by unlight** [comment]
@yassinebridi `emitDecoratorMetadata` is creating such problem

```ts
class User {
    @Field(() => Post)
    post!: Post;
}
class Post {
    @Field(() => User)
    user!: User;
}
```

```js
class User {
}
__decorate([
    Field(() => Post),
    __metadata("design:type", Post)
], User.prototype, "post", void 0);
class Post {
}
__decorate([
    Field(() => User),
    __metadata("design:type", User)
], Post.prototype, "user", void 0);
```

`__metadata` tries immediately access to class, (it's not lazy like `Field`).

I guess you cannot disable it, since NestJS depends on it.
So, it means `emitSingle` and `emitCompiled` cannot be enabled together. I'll update documentation.

I just figure out how it can be solved, using weird trick:

```
class User {
    @Field(() => Post)
    post!: InstanceType<typeof Post>;
}
class Post {
    @Field(() => User)
    user!: InstanceType<typeof User>;
}
```

It will generate `__metadata("design:type", void 0)`
