### ISSUE TITLE
ModelAggregateArgs is no more supported

### ISSUE THREAD

**Issue by marmik18** [unlight/prisma-nestjs-graphql#153]
Hi there, 

I have recently upgraded to from `v16.x` to `v17.x` and I found out that the `AggregateArgs` are not being generated.
Is there a reason for this, or something was missed in the recent releases? 

Thank you for your time in advance :)

**Comment by marmik18** [comment]
Update: upon inspecting further, I found out this is only the case with some of the models and not all

**Comment by unlight** [comment]
Is issue still actual?

**Comment by marmik18** [comment]
Sorry, I am not so sure. I have not worked on prisma for a while now.
Closing the issue.
