### ISSUE TITLE
Generate only model

### ISSUE THREAD

**Issue by Hetch3t** [unlight/prisma-nestjs-graphql#156]
Is there a way or a flag to generate only classes for models (without generating outputs, inputs etc.)?

**Comment by unlight** [comment]
No.
But you can add additional step to generation process.
1. Configure
```
outputFilePattern = "/tmp/{name}.{type}.ts"
```
2. npx prisma generate
3. cp /tmp/*.model.ts /src/@generated
4. /tmp/*-count.output /src/@generated
