### ISSUE TITLE
Deprecated `Decimal` import

### ISSUE THREAD

**Issue by hbriese** [unlight/prisma-nestjs-graphql#160]
## Problem

```ts
imports from "@prisma/client/runtime" are deprecated.

> 1 | import { Decimal } from '@prisma/client/runtime';
```

## Solution
Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"

**Comment by unlight** [comment]
Could you point to documentation where is the recomended way to import decimal?
I found https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields#working-with-decimal
```
import { PrismaClient, Prisma } from '@prisma/client'

const newTypes = await prisma.sample.create({
  data: {
    cost: new Prisma.Decimal(24.454545),
  },
})
```

**Comment by hbriese** [comment]
Apologies, Apparently this is a [Prisma issue](https://github.com/prisma/prisma/issues/18101) and will be fixed in the next version

Both problem and the solution were console logged by Prisma.
