### ISSUE TITLE
Deprecation Warnings 

### ISSUE THREAD

**Issue by jasonmacdonald** [unlight/prisma-nestjs-graphql#161]
HI, the following hard-coded imports `importDeclarations.add('Decimal', '@prisma/client/runtime');` are causing deprecation warnings with Prisma 4.10+.  

```bash
console.warn
   imports from "@prisma/client/runtime" are deprecated.
   Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"

    > 13 | import { Decimal } from '@prisma/client/runtime';
```

I've tracked the issues to a few files, all of which have to do with Decimal. 

https://github.com/unlight/prisma-nestjs-graphql/blob/1f1ef9c39a2db9f86d83788cfc0eae2d9f55cda6/src/handlers/input-type.ts#L118
https://github.com/unlight/prisma-nestjs-graphql/blob/b83beeb15b289ee80d5ed96004273228625fab38/src/handlers/model-output-type.ts#L159
https://github.com/unlight/prisma-nestjs-graphql/blob/b83beeb15b289ee80d5ed96004273228625fab38/src/handlers/model-output-type.ts#L159

Note that unlike mentioned in https://github.com/unlight/prisma-nestjs-graphql/issues/160, updating, deleting node_modules, and reinstalling does not make the issue go away. It's always in the freshly generated file due to it being in the code :) 

The tricky part to solving this is that the `engineType` defined In the `package.json` now drives which to use.

Or am I missing something?

**Comment by unlight** [comment]
https://github.com/unlight/prisma-nestjs-graphql/releases/tag/v18.0.0
