### ISSUE TITLE
EMFILE: too many open files (Windows)

### ISSUE THREAD

**Issue by And2s** [unlight/prisma-nestjs-graphql#162]
Hi, I've got  `EMFILE: too many open files, open '********.input.ts'`.

I monkey patched fs with graceful-fs by editing `node_modules/prisma-nestjs-graphql/index.js` and adding the code below. It works fine then.

```
var realFs = require('fs')
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(realFs);
```

Error happens on Windows. On MacOS it works fine.

Reproduction would probably need a large schema. Mine has 150+ tables.

Tested with 17.1.0 and 18.0.0

**Comment by And2s** [comment]
Still happens on 18.0.2. I resolved with the same global patch as before. Maybe it's `prisma` issue and not this lib?

**Comment by 50l3r** [comment]
Still happens on `20.0.3`
