### ISSUE TITLE
Cannot use this package directly in other prisma generator

### ISSUE THREAD

**Issue by floross** [unlight/prisma-nestjs-graphql#169]
We are building generators and we want to leverage your dtos and use them with some preconfigured options. Right now when we try to use your package we cannot use the generate function only.

Moreover no types are exported for the moment.

I made a PR to export the generate file only (without the index): https://github.com/unlight/prisma-nestjs-graphql/pull/168

So with this changes we could to this:

```ts
import { generate } from 'prisma-nestjs-graphql/generate';
```

**Comment by unlight** [comment]
`import { generate } from 'prisma-nestjs-graphql/generate';`

Is this typescript source or js?

**Comment by unlight** [comment]
This lib does not provide esm modules

**Comment by unlight** [comment]
See #168
