### ISSUE TITLE
swc circular dependency issue 

### ISSUE THREAD

**Issue by okaisti** [unlight/prisma-nestjs-graphql#175]
when trying out swc, I'm getting the error:  

> Cannot access 'X' before initialization

Possibly relates to:
https://docs.nestjs.com/recipes/swc#common-pitfalls

is there a way to get nest swc to work with prisma-nestjs-graphql?

**Comment by unlight** [comment]
Have you tried `emitCompiled` option?

> is there a way to get nest swc to work with prisma-nestjs-graphql?

If you generating ts files, then I'm afraid that it's not possible.

You can separate generated ts files to other project and compile them by `tsc`.

**Comment by dotoleeoak** [comment]
> Have you tried `emitCompiled` option?

This helped me! Thank you 😆

**Comment by dotoleeoak** [comment]
Unfortunately, in my case, `emitCompiled` option coluld not solve the problem completely. 
I investigated to this more, and this issue seems to be related.
https://github.com/nestjs/graphql/issues/2568
