### ISSUE TITLE
Wrong location of generated assets if model names overlap

### ISSUE THREAD

**Issue by iamciroja** [unlight/prisma-nestjs-graphql#180]
First of all, thank you for a great library :)

I have noticed that under certain conditions regarding model names the assets are generated in wrong folders.

Steps to reproduce the bug

1. Clone this repository and change current directory to it.
2. Run `npm install` 
3. Run `npm run regen` to trigger generation of assets according to default schema located at ./prisma/prisma.schema
4. After generation is complete, look at the @generated folder. Everything is fine, generator works as expected.
5. Open prisma/prisma.schema and add any model with the name that a) starts with the name of existing model, and b) is exactly 7 letters longer. For example, let's add the following model

```
model UserAbcdefg{
  id String @id
  abc String
}

```
6. Run `npm run regen` once again then look at @generated folder.

You can see that @generated/user-abcdefg folder is missing several *.args.ts types that are related to newly created UserAbcdefg.
Now look at @generated/user - and you will find these types there.

It seems that the problem is in getModelName helper that incorrectly determines the name of the model.
The block starting from [this line](https://github.com/unlight/prisma-nestjs-graphql/blob/ed40f139cd015f05e35466930279147e282e7d88/src/helpers/get-model-name.ts#L28) cuts the chunks from the start and the end of type name and then tries to find the rest in list of known model names.
So given the **name**=CreateManyUserAbcdefgsArgs, start=FindUnique, end=OrThrowArgs it cuts 10 symbols (length of FindUnique) from start and 11 symbols (length of OrThrowArgs) from the end of CreateManyUserAbcdefgsArgs and makes a conclusion that the name of model is User.

**Comment by iamciroja** [comment]
Also it seems that [this PR](https://github.com/unlight/prisma-nestjs-graphql/pull/181) would fix this issue

**Comment by unlight** [comment]
Thanks. Fixed in 18.1.1
