### ISSUE TITLE
v11.1 as a pre-release

### ISSUE THREAD

**Issue by lukadriel7** [unlight/prisma-nestjs-graphql#19]
Hello, I saw that the version 11.1 was a pre-release.
is there an estimated to when to expect the full release ?
Thank you for your hard work, this is a great library

**Comment by unlight** [comment]
Hi. 
What feature from pre-prelease are you interested in? I suspect custom decorators... Does it work for you?

I can release but I am waiting resolution of https://github.com/prisma/prisma/issues/3102
Looks like there is no much movement there

**Comment by lukadriel7** [comment]
Exactly, I am really interested in custom decorators. About the prisma side, it seems like they don't plan to work on it soon. I think the current plan was to make a preview of mongodb support so I am not sure they are currently looking into it

**Comment by unlight** [comment]
Released 11.2.0 with custom decorators feature.
