### ISSUE TITLE
prismaClientImport not working

### ISSUE THREAD

**Issue by anissouissi** [unlight/prisma-nestjs-graphql#202]
Hello,

When I add this configuration:
prismaClientImport      = "@prisma/catalog"

I still get import { Prisma } from '@prisma/client'; in my generated file.

I was expecting to have import { Prisma } from '@prisma/catalog'; in the generated file.

**Comment by roelbeerens** [comment]
That feature is only working in 19.3.0, but that one hasn't been officially released yet. @unlight Is there an ETA when that version will be released?

**Comment by unlight** [comment]
Something happedned with semantic-release publish script.
Please try the latest version `20.0.2`

**Comment by anissouissi** [comment]
Thanks @unlight 
I update to version 20.0.2
Now the issue is fixed
