### ISSUE TITLE
Question: How should I deal with undefined and null mismatch

### ISSUE THREAD

**Issue by lutaalbert** [unlight/prisma-nestjs-graphql#21]
I have a User model with an optional(nullable) avatar field:
```prisma
model User {
    id            String @id @default(cuid())
    name          String
    email         String @unique
    avatar        Bytes?
    /// @HideField()
    password      String
}
```
and a simple resolver method which gets an user by id:
```ts
@Query(() => User, { nullable: true })
user(@Args('id') id: string): Promise<User | null> {
    return this.prisma.user.findUnique({ where: { id } });
}
```
and I get this error:
![image](https://user-images.githubusercontent.com/55731599/115150525-6fa89580-a071-11eb-9b44-b1d06b63298e.png)

Am i missing something here or the types are not compatible?

**Comment by unlight** [comment]
They are incompatible.

But it is possible to make it compatible.

**Comment by unlight** [comment]
Option to set undefined rather than null with the ? schema operator https://github.com/prisma/prisma/issues/6586
