### ISSUE TITLE
5.14.0 error: `Cannot find model by name CreateManyUserAndReturnOutputType`

### ISSUE THREAD

**Issue by Weakky** [unlight/prisma-nestjs-graphql#214]
## Overview

Hey, we're releasing Prisma 5.14.0 tomorrow and we've noticed that your generator is broken with that version. Specifically, `generate` fails with the following error:

```
$ pnpm prisma generate

Prisma schema loaded from prisma/schema.prisma
Error: 
Cannot find model by name CreateManyUserAndReturnOutputType

✔ Generated Prisma Client (v5.14.0-dev.71) to ./node_modules/.pnpm/@prisma+client@5.14.0-dev.71_prisma@5.14.0-dev.71/node_modules/@prisma/client in 32ms
```

This seems to come after the addition of the `createManyAndReturn` operation.

It can be reproduced [here](https://github.com/prisma/ecosystem-tests/tree/dev/community-generators/prisma-nestjs-graphql) by running the `run.sh` script.

Let us know if we can help, cheers!

**Comment by hcharley** [comment]
I too am seeing this, just FYI.

**Comment by Mario2280** [comment]
+1

**Comment by 0-don** [comment]
same problem
