### ISSUE TITLE
Updates with Set property 

### ISSUE THREAD

**Issue by AndrewAllison** [unlight/prisma-nestjs-graphql#22]
I'm not sure where to put this as it's not really an issue but a question, so sorry if this is the wrong place.

```bash
"message": "Variable \"$roleDetails\" got invalid value \"Stuff thatt should work\" at \"roleDetails.description\"; Expected type \"StringFieldUpdateOperationsInput\" to be an object.",
```

I recently updated to the latest version of prisma and prisma-nestjs-graphql since then I receive errors on updates where the properties are now of type `StringFieldUpdateOperationsInput` meaning I have to change all my update operations to have a `.set` property. Do you have a property to stop this happening or any advice on how to work with updates going forward. I have a not large codebase and the app isn't production ready yet but I just want to know what the advice is for how to deal with this going forward.

Thanking you kindly

**Comment by unlight** [comment]
Most likely you updated from < 10.0.0 where `noAtomicOperations` (name was diferent) configuration was enabled by default.
Please, check option noAtomicOperations - https://github.com/unlight/prisma-nestjs-graphql#noatomicoperations

**Comment by AndrewAllison** [comment]
That was the one. Thank you so much for this and the library as a whole.
