### ISSUE TITLE
Expected output in default configuration?

### ISSUE THREAD

**Issue by janpio** [unlight/prisma-nestjs-graphql#24]
Just added a test for this generator to prisma/e2e-tests (still WIP), and wanted to confirm the output I am seeing (as I do not know much about NestJS):

Is it correct that using this will output 1 folder per model, and 1 `prisma` folder, all containing a bunch of files?

Thanks.

**Comment by unlight** [comment]
Yes, that it correct. It is default output configuration splitting all files by model, prisma folder for common files like scalar filters, enums, etc.

Output folders can be configured by `outputFilePattern` option - https://github.com/unlight/prisma-nestjs-graphql#outputfilepattern

**Comment by janpio** [comment]
Thanks.
