### ISSUE TITLE
Dependency on prisma client js generator?

### ISSUE THREAD

**Issue by janpio** [unlight/prisma-nestjs-graphql#25]
Just added a test for this generator to prisma/e2e-tests (still WIP), and stumbled over the dependency for the prisma-client-js generator. Why does this exist? Or is this only to make sure that on runtime everything works as expected (and using the Prisma Client is possible)?

**Comment by unlight** [comment]
It exists from the beginning. I found that DMMF which passes to generator is different than dmmf from prisma client. And using prisma client dmmf was more useful.

I'll check possibility to get rid of it.

**Comment by janpio** [comment]
Ah ok, that makes sense and it something we should probably be aware of internally as well as a possible problem or thing that could be improved.

**Comment by unlight** [comment]
I did some investigation. Currently, dmmf data looks the same, I think I can get rid of `prisma-client-js`, with tiny modification of code related to meta comments. All unit tests are passing.

**Comment by unlight** [comment]
@janpio 
Could you elaborate what is the issue of using prisma-client-js as dependency?

After closer look I found that dmmf is different if preview features are used.

So, technically prisma-client-js is not necessary, and prisma-nestjs-graphql will work without it. But result can be different.

**Comment by janpio** [comment]
No issue at all, it was just surprising as my test project would not require Prisma Client and so I got an error message. If you decide that is better for this library, so be it - you have a nice error message when it is missing, so easy enough to uncover and fix.
