### ISSUE TITLE
Error "Input Object must define one or more fields"

### ISSUE THREAD

**Issue by DennieMello** [unlight/prisma-nestjs-graphql#26]
If you create a schema in which there will be no editable fields, then an error appears - "Input Object must define one or more fields". I think it won't be difficult to fix it.

![Снимок экрана 2021-05-05 в 23 30 54](https://user-images.githubusercontent.com/39631512/117205460-54bc7c00-adfa-11eb-9879-1d3103d87919.jpg)

![Снимок экрана 2021-05-05 в 23 30 00](https://user-images.githubusercontent.com/39631512/117205486-5c7c2080-adfa-11eb-8115-e642749d6d65.jpg)

![Снимок экрана 2021-05-05 в 23 30 40](https://user-images.githubusercontent.com/39631512/117205477-5a19c680-adfa-11eb-9df3-f47570596fd8.jpg)

**Comment by unlight** [comment]
Just simple single model with @default(autoincrement()) generates empty class.

```
model User {
   id  Int  @id  @default(autoincrement())
}
```
Prisma generates empty class too.

![image](https://user-images.githubusercontent.com/301732/117224115-3c5f5800-ae20-11eb-8e87-6ad87a9a41d5.png)

I'm going to forward it to prisma team.

**Comment by unlight** [comment]
https://github.com/prisma/prisma/issues/6967

**Comment by unlight** [comment]
Why you decided to keep favorites in separate model, instead of many to many relations?
```
model User {
	favoriteComments Comment[]
    favoritePosts Posts[]
}

model Comment {
   favoritedBy User[]
}

model Post {
   favoritedBy User[]
}

```
