### ISSUE TITLE
The resulting .ts class files are missing the import for the enum, everything else is there ?

### ISSUE THREAD

**Issue by adamrogas** [unlight/prisma-nestjs-graphql#3]
I am using 2.0.0 of the library and everything was working great until I tried to use enums, am I missing something or is this a bug.

model Token {
  token           String            @id
  createdAt       DateTime          @default(now())
  updatedAt       DateTime          @updatedAt
  owner           Team              @relation(fields: [ownerId], references: [id])
  ownerId         String
  docs            CredentialModel[] @relation(name: "docKey")
  credentials     CredentialModel[] @relation("key")
}

model CredentialModel {
  id          String                 @id @default(cuid())
  createdAt   DateTime               @default(now())
  updatedAt   DateTime               @updatedAt
  displayName String
  logo        String?
  key         Token                  @relation(name: "key", fields: [keyId], references: [token])
  keyId       String
  docsKey     Token?                 @relation(name: "docKey", fields: [docKeyId], references: [token])
  docKeyId    String?
  scopes      CredentialModelScope[]
  precedents  CredentialModel[]      @relation(name: "precedents", references: [id])
  descendants  CredentialModel[]      @relation(name: "precedents", references: [id])
  properties  ModelProps[]

  owner   Team   @relation(fields: [ownerId], references: [id])
  ownerId String
}

model CredentialModelScope {
  id                String           @id @default(cuid())
  createdAt         DateTime         @default(now())
  updatedAt         DateTime         @updatedAt
  scope             String
  CredentialModel   CredentialModel? @relation(fields: [credentialModelId], references: [id])
  credentialModelId String?
}

enum SymanticPropTypes {
  Boolean
  Collection
  Color
  DateTime
  FixedCollection
  Hidden
  Json
  MultiOptions
  Number
  Options
  String
}

enum EditorUITypes {
  Code
}

model ModelPropsUIOptions {
  id            String      @id @default(cuid())
  show          Boolean
  key           String
  valueAsString String?
  valueAsNumber Int?
  valueAsBool   Boolean?
  valueNull     Boolean     @default(false)
  ModelProps    ModelProps? @relation(fields: [modelPropsId], references: [id])
  modelPropsId  String?
}

model ModelPropOptions {
  id            String       @id @default(cuid())
  key           String
  description   String?
  displayName   String?
  valueAsString String?
  valueAsNumber Int?
  valueAsProp   ModelProps?  @relation(name: "valueAsProp", fields: [valueAsPropId], references: [id])
  valueAsPropId String?
  valueAsProps  ModelProps[]
}

model ModelProps {
  id                       String                  @id @default(cuid())
  displayName              String
  name                     String                 
  type                     SymanticPropTypes
  typeOptions              ModelPropExtensionData? @relation(fields: [modelPropExtensionDataId], references: [id])
  default                  Json //NodeParameterValue | INodeParameters | INodeParameters[] | NodeParameterValue[];
  description              String?
  uiOptions                ModelPropsUIOptions[]
  options                  ModelPropOptions[]
  placeholder              String?
  isWorkerSetting          Boolean?
  noDataExpression         Boolean?
  required                 Boolean?
  ModelPropOptions         ModelPropOptions[]      @relation("valueAsProp")
  modelPropExtensionDataId String?
}

model ModelPropExtensionData {
  id                      String                      @id @default(cuid())
  forceEditWindow         Boolean?
  editor                  EditorUITypes?
  loadOptionsDependsOn    String[]
  loadOptionsMethod       String?
  maxValue                Int?
  minValue                Int?
  multipleValues          Boolean?
  multipleValueButtonText String?
  numberPrecision         Int?
  numberStepSize          Int?
  password                Boolean?
  rows                    Int?
  ex                      ModelPropExtensionOptions[]
  ModelProps              ModelProps[]
}

model ModelPropExtensionOptions {
  id                       String                  @id @default(cuid())
  key                      String
  valueAsString            String?
  valueAsNumber            Int?
  valueAsBool              Boolean?
  valueAsEditor            EditorUITypes?
  valueAsStrings           String[]
  ModelPropExtensionData   ModelPropExtensionData? @relation(fields: [modelPropExtensionDataId], references: [id])
  modelPropExtensionDataId String?
}

**Comment by unlight** [comment]
@adamrogas 
Enums should work, I have tested it.

But to use enums you must import enum file, check
https://docs.nestjs.com/graphql/enums

For example, we have generated `src/@generated/prisma/sort-order.enum.ts`
```ts
import { registerEnumType } from '@nestjs/graphql';

export enum SortOrder {
    asc = 'asc',
    desc = 'desc',
}

registerEnumType(SortOrder, { name: 'SortOrder', description: undefined });

```

So, `src/@generated/prisma/sort-order.enum` must be imported somewhere in your code, otherwise `registerEnumType` will never be called, therefore no enum in graphql schema.

Is it your case? Did you import enum with `registerEnumType`?

**Comment by unlight** [comment]
Look likes you did not specify full schema
```
Error: Schema parsing
error: Type "Team" is neither a built-in type, nor refers to another model, custom type, or enum.
```

**Comment by adamrogas** [comment]
Sorry I omitted a couple of the classes, the problem I am running into is after the generator runs and generates the classes the classes that include the Enums in their union types do not compile to JS because they are missing the ref to the Enum the enums are generated but they are not imported in the classes that use them and so I get errors like 

src/models/model-prop-extension-data/model-prop-extension-data-update-without-model-props-data.input.ts:25:14 - error TS2304: Cannot find name 'EditorUITypes'.

25     editor?: EditorUITypes | NullableEnumEditorUITypesFieldUpdateOperationsInput | null;
                ~~~~~~~~~~~~~

Full Prisma Schema Below
-----------

generator client {
  provider = "prisma-client-js"
}

generator nestgraphql {
  provider = "node node_modules/prisma-nestjs-graphql"
  output   = "../src/models"
}

generator dbml {
  provider = "prisma-dbml-generator"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model Project {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  name      String
  flows     Flow[]
  team      Team     @relation(fields: [teamId], references: [id])
  teamId    String
}

model Team {
  id              String            @id @default(uuid())
  createdAt       DateTime          @default(now())
  updatedAt       DateTime          @updatedAt
  name            String
  logo            String?
  users           User[]            @relation("teamMembership")
  teamSize        String?
  credentials     Credential[]
  projects        Project[]
  lastUsers       User[]            @relation("lastTeamId")
  Token           Token[]
  CredentialModel CredentialModel[]
}

model User {
  id        String   @id @default(uuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  username String @unique

  /// Profile email address of the user
  email String

  /// Full name of the user
  name String

  /// Last team the user selected in the UI
  lastTeam Team? @relation(name: "lastTeamId", fields: [lastTeamId], references: [id])

  lastTeamId String?

  role String?

  /// Profile picture URL
  picture String?

  /// Profile picture URL
  remotePicture String?

  credentials Credential[]

  flows Flow[]

  teams Team[] @relation("teamMembership")

}
// model TeamMapping{

// }

model Credential {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  data      Json
  owner     User?    @relation(fields: [userId], references: [id])
  team      Team?    @relation(fields: [teamId], references: [id])
  userId    String?
  private   Boolean
  teamId    String?
}

model Token {
  token           String            @id
  createdAt       DateTime          @default(now())
  updatedAt       DateTime          @updatedAt
  owner           Team              @relation(fields: [ownerId], references: [id])
  ownerId         String
  docs            CredentialModel[] @relation(name: "docKey")
  credentials     CredentialModel[] @relation("key")
}

model CredentialModel {
  id          String                 @id @default(cuid())
  createdAt   DateTime               @default(now())
  updatedAt   DateTime               @updatedAt
  displayName String
  logo        String?
  key         Token                  @relation(name: "key", fields: [keyId], references: [token])
  keyId       String
  docsKey     Token?                 @relation(name: "docKey", fields: [docKeyId], references: [token])
  docKeyId    String?
  scopes      CredentialModelScope[]
  precedents  CredentialModel[]      @relation(name: "precedents", references: [id])
  descendants  CredentialModel[]      @relation(name: "precedents", references: [id])
  properties  ModelProps[]

  owner   Team   @relation(fields: [ownerId], references: [id])
  ownerId String
}

model CredentialModelScope {
  id                String           @id @default(cuid())
  createdAt         DateTime         @default(now())
  updatedAt         DateTime         @updatedAt
  scope             String
  CredentialModel   CredentialModel? @relation(fields: [credentialModelId], references: [id])
  credentialModelId String?
}

enum SymanticPropTypes {
  Boolean
  Collection
  Color
  DateTime
  FixedCollection
  Hidden
  Json
  MultiOptions
  Number
  Options
  String
}

enum EditorUITypes {
  Code
}

model ModelPropsUIOptions {
  id            String      @id @default(cuid())
  show          Boolean
  key           String
  valueAsString String?
  valueAsNumber Int?
  valueAsBool   Boolean?
  valueNull     Boolean     @default(false)
  ModelProps    ModelProps? @relation(fields: [modelPropsId], references: [id])
  modelPropsId  String?
}

model ModelPropOptions {
  id            String       @id @default(cuid())
  key           String
  description   String?
  displayName   String?
  valueAsString String?
  valueAsNumber Int?
  valueAsProp   ModelProps?  @relation(name: "valueAsProp", fields: [valueAsPropId], references: [id])
  valueAsPropId String?
  valueAsProps  ModelProps[]
}

model ModelProps {
  id                       String                  @id @default(cuid())
  displayName              String
  name                     String                 
  type                     SymanticPropTypes
  typeOptions              ModelPropExtensionData? @relation(fields: [modelPropExtensionDataId], references: [id])
  default                  Json //NodeParameterValue | INodeParameters | INodeParameters[] | NodeParameterValue[];
  description              String?
  uiOptions                ModelPropsUIOptions[]
  options                  ModelPropOptions[]
  placeholder              String?
  isWorkerSetting          Boolean?
  noDataExpression         Boolean?
  required                 Boolean?
  ModelPropOptions         ModelPropOptions[]      @relation("valueAsProp")
  modelPropExtensionDataId String?
}

model ModelPropExtensionData {
  id                      String                      @id @default(cuid())
  forceEditWindow         Boolean?
  editor                  EditorUITypes?
  loadOptionsDependsOn    String[]
  loadOptionsMethod       String?
  maxValue                Int?
  minValue                Int?
  multipleValues          Boolean?
  multipleValueButtonText String?
  numberPrecision         Int?
  numberStepSize          Int?
  password                Boolean?
  rows                    Int?
  ex                      ModelPropExtensionOptions[]
  ModelProps              ModelProps[]
}

model ModelPropExtensionOptions {
  id                       String                  @id @default(cuid())
  key                      String
  valueAsString            String?
  valueAsNumber            Int?
  valueAsBool              Boolean?
  valueAsEditor            EditorUITypes?
  valueAsStrings           String[]
  ModelPropExtensionData   ModelPropExtensionData? @relation(fields: [modelPropExtensionDataId], references: [id])
  modelPropExtensionDataId String?
}

model Flow {
  id        String   @id @default(cuid())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  data      Json
  project   Project  @relation(fields: [projectId], references: [id])
  owner     User     @relation(fields: [userId], references: [id])
  userId    String
  projectId String
}

**Comment by adamrogas** [comment]
![image](https://user-images.githubusercontent.com/5152077/98726396-4d388080-234b-11eb-9c57-53c875e724f2.png)

and the generated class is missing the import hence the compile error

**Comment by unlight** [comment]
Thanks, I can reproduce it now.
The reason: nullable enum I did not take such type.
