### ISSUE TITLE
Only generate model

### ISSUE THREAD

**Issue by TkinterinShanghai** [unlight/prisma-nestjs-graphql#32]
I only want to generate the model and not all different input types that I may or may not use. Is there a configuration option for that? Because I didnt find one looking at the documentation here. npx prisma generate creates a lot of types although i just want the objects so far

Furthermore, I would like to exclude some fields that are present in the prisma model from the model in typegraphql. I do not want to have the relations.

```
model User {
  userId             Int                  @id @default(autoincrement()) @map("user_id")
  createdAt          DateTime             @default(dbgenerated("CURRENT_DATE")) @map("created_at") @db.Date
  emailConfirmed     Boolean              @default(false) @map("email_confirmed")
  email              String               @unique @db.VarChar(255)
  ///@HideField({ input: true, output: true })
  password           String
  ///@HideField({ input: true, output: true })
  UserExercise       UserExercise[]
 
  @@map("user_info")
}
```

creates this user.model.ts

```
@ObjectType()
export class User {
    @Field(() => ID, {nullable:false})
    userId!: number;

    @Field(() => Date, {nullable:false})
    createdAt!: Date;

    @Field(() => Boolean, {nullable:false,defaultValue:false})
    emailConfirmed!: boolean;

    @Field(() => String, {nullable:false})
    email!: string;

    @HideField()
    password!: string;

    @HideField()
    UserExercise!: Array<UserExercise>;
}

```

but i do not want the UserExercise field in my ObjectType because if i want to specify the return type of my resolver like this

```
@Resolver(() => User)
export class UserResolver {
  constructor(private prisma: PrismaService) {}
  async user(): Promise<User> {
  ...
}
```

The user in Promise<User> is expected to include the referenced UserExercise, which it wont have

**Comment by unlight** [comment]
There is no such option to generate only models.
But you can configure outputFilePattern like `{plural.type}/{name}` models will be saved to one folder 'models'.

About userexcersize error. Is it typescript error or graphql error?
There is no option for removing specific fields?

**Comment by TkinterinShanghai** [comment]
@unlight yeah I have already configured the outputfilepattern. Nice job on that by the way! I really like this functionality! And I already used this to separate my model from the rest. The error I got was a typescript error but I guess I'll just have to set my return type to omit<User, "all the stuff I don't want" >.

**Comment by unlight** [comment]
If can modify `UserExercise` property and make it optional, `UserExercise?: Array<UserExercise>`
Second generation over existing files should not override properties in model (at least it was so intended by design).

But if you need only models and they are heavy modified from first generation, maybe it's better you use generator once and then maintain models by hand.

**Comment by TkinterinShanghai** [comment]
Yeah, I guess this is the way to go
