### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by essarn** [unlight/prisma-nestjs-graphql#35]
Hi, awesome package 🚀 

Is it possible to generate input types for paging with `findMany`?
Maybe this is already supported but can not find anything in the docs.

Thanks!

**Comment by essarn** [comment]
Literally, five minutes later I found that a `FindMany_Args` is generated! 😮 
No need to stitch all the inputs together manually then.

Again, so awesome package!

**Comment by kasir-barati** [comment]
Hi @kansson,

Thanks for the follow up comment, BTW do you know how we can implement Cursor-based Connections pagination with this lib? I mean for the nested fields inside another model, e.g. if I have `Post` and `Comment` models I will end up with `CommentRelationFilter` in my `PostWhereInput` which does not have pagination fields. Yes, I can kinda do a quick patch work and put things together but I was wondering if others have done something more robust and maintainable.

**Comment by kansson** [comment]
Hello @kasir-barati unfortunately I'm not using graphql anymore so I'm not sure.

**Comment by kasir-barati** [comment]
JFYI, I managed to do it. Find more info here: https://github.com/kasir-barati/graphql-js-ts/blob/main/docs/best-practices/pagination.md
