### ISSUE TITLE
Optional one-to-many relation generates NON-nullable field

### ISSUE THREAD

**Issue by antoineharel** [unlight/prisma-nestjs-graphql#38]
Hi there !
Thank you for this package, it is very helpful.

In my application, I have a `User` model, which has a relation to `Team` model. It is a one-to-many relation (users can have a team or not, and teams have 0 or more users) :

![image](https://user-images.githubusercontent.com/52471363/124489200-06533b80-ddb1-11eb-9263-641258b0a9f7.png)

However, on the generated `User` GraphQL model, the `team` and `teamId` fields are marked as non-nullable :

![image](https://user-images.githubusercontent.com/52471363/124490020-ea9c6500-ddb1-11eb-857f-be30412408c3.png)

This can lead to errors when querying these fields on users for which they are `null`.

Is this the intended behaviour ? And if so, could you explain me why ? 

Thanks ! ❤️

**Comment by unlight** [comment]
The second screenshot, what is the name of this class?

**Comment by antoineharel** [comment]
> The second screenshot, what is the name of this class?

It is the generated `User` @ObjectType class, generated from the `User` model in my Prisma schema:

![image](https://user-images.githubusercontent.com/52471363/124500462-1fafb400-ddc0-11eb-9ad4-cab2ad3b358b.png)

**Comment by unlight** [comment]
Did you change field team from required to nullable, and then ran npx prisma generate? If yes, try to remove `user.model.ts` and run `npx prisma generate` again.

**Comment by antoineharel** [comment]
Oh, that did the trick, I guess the GraphQL class was not re-generated after changing the field to optional in my prisma schema !

Thank you, it worked like a charm ! 💯

**Comment by unlight** [comment]
Generator initially designed for as well as update existing source code. So for `.model.ts` files it does not update property (including types and decorators) if it already exists in the class.

I'll try to reflect this behavior in documentation.

Next time, just remove all generated files before running `npx prisma generate`
