### ISSUE TITLE
Comments in generated types

### ISSUE THREAD

**Issue by jsbrain** [unlight/prisma-nestjs-graphql#39]
Is it possible to emit the model descriptions/comments in the generated types?

I mean, they are there in the `@Field()` annotation but I would require them as pure comment as well so they can be picked up by the NestJS Swagger plugin to have them in the generated docs. Seems like this isn't working, at least not for me.

I tried different combinations of the config but apparently this is not a feature (yet)?

Or is there maybe a way to make swagger pick up the descriptions from the `@Field()` annotations? 🤔

**Comment by unlight** [comment]
I dont think that swagger (Open API) and graphql are compatible.
If we have graphql, all documentation goes via graphql schema comments.

Or maybe I'm getting it wrong can you provide example?

**Comment by jsbrain** [comment]
Well yes, I'm actually using this library just for the dto generation from my prisma schema. I'm not using graphql at all but using the normal REST pattern. Apparently, this is library suites my use case pretty good, the only thing missing is the comments and everything would work just fine.

See, currently I get this:

```ts
@ObjectType()
export class FunnelAccount {
  @Field(() => ID, { nullable: false })
  id!: string;

  @Field(() => AccountType, { nullable: false })
  type!: AccountType;

  @Field(() => String, {
    nullable: false,
    description: 'Name or identifier of the account.',
  })
  name!: string;
}
```

what I want to get is this:

```ts
@ObjectType()
export class FunnelAccount {
  @Field(() => ID, { nullable: false })
  id!: string;

  @Field(() => AccountType, { nullable: false })
  type!: AccountType;

  @Field(() => String, {
    nullable: false,
    description: 'Name or identifier of the account.',
  })
  name!: string;
}
```

**Comment by unlight** [comment]
I'll check possibility to duplicate comment in jsdoc section.
