### ISSUE TITLE
Abstract and renamed @ObjectType('<name>')

### ISSUE THREAD

**Issue by silveiralsv** [unlight/prisma-nestjs-graphql#40]
Please, I was looking for a option that can rename the generated @ObjectType and possibly turn it into an abstract class({isAbstract: true}).

E.g:
```
/// @Name: MyGeneratedModel
model MyModel{
  id         Int    @id @default(autoincrement())
```

Generate something like: 
```
@ObjectType('MyGeneratedModel')
export class MyModel{ }
```

And I was looking for something similar for creating abstract classes, eg:
```
/// @IsAbstract
model MyModel{
  id         Int    @id @default(autoincrement())
```
Generate:
```
@ObjectType({isAbstract: true})
export class MyModel{ }
```

Idk if this where implemented, but i couldn't find on the read me. 
@unlight if there are such options, please tell me 🙂

thx

**Comment by unlight** [comment]
There is no options to rename class or make it abstract.

**Comment by unlight** [comment]
How it will work? After adding `{ isAbstract: true }` I'm still seeing this type in schema.

**Comment by unlight** [comment]
Renaming - yes it is working. Possible to do.

**Comment by unlight** [comment]
@moraisp 
@silveiralsv 
How do you use isAbstract option? Are you apllying it for all models or for some of them?

**Comment by moraisp** [comment]
It's specially useful on ObjectTypes since it's very common to extend and reuse the same name as the original.
Although I don't see why not doing an input/output configuration.

```typescript
// if GeneratedUserModel is not an abstract class we would have conflicting model names.
@ObjectType()
class UserModel extends GeneratedUserModel {}

// and this would include both ObjectTypes in the sdl
@ObjectType()
class CustomUserModel extends GeneratedUserModel {}
```

Also worth noticing that using an abstract model as type turns it into the "real thing". 
My team had to `@HideInput` on all model relationships or else any attempt to extend the abstract generated model would end in a sdl conflict.
```typescript
class UserModel {
    // Group is abstract but gets included in the sdl
    @Field(() => [GroupModel], {nullable:false})
    groups!: Array<GroupModel>;
}
```
