### ISSUE TITLE
Type mismatch: Optional field should have a '?' modifier

### ISSUE THREAD

**Issue by mngu** [unlight/prisma-nestjs-graphql#41]
Hi,

First thanks for this package !
I am running into a type mismatch with generated optional fields.

Here is my `schema.prisma`:
```javascript
model User {
  id              Int       @id @default(autoincrement())
  ...
  member          Member?
}

model Member {
  id                  Int                 @id @default(autoincrement())
  ...
  user                User                @relation(fields: [userId], references: [id])
  userId              Int
}
```
The generated model looks like:
```javascript
@ObjectType()
export class User {
  @Field(() => ID, { nullable: false })
  id!: number;

  ...

  @Field(() => Member, { nullable: true })
  member!: Member;
}
```
If I use this model in a service:
```javascript
async firstUser(userWhereInput: Prisma.UserWhereInput): Promise<User | null> {
  return this.prisma.user.findFirst({
    where: userWhereInput,
  });
}
```
I have this typescript error: 
```
TS2739: Type 'User' is missing the following properties from type 'User': member
```
Shoudn't the generated field have a `?` modifier ?
```javascript
  @Field(() => Member, { nullable: true })
  member?: Member;
```

Thanks for your help

**Comment by unlight** [comment]
Try to remove generated files and run generated again. See #38 looks like it same

**Comment by mngu** [comment]
Yes, I tried to delete the whole `@generated` folder and re-run `generate`, but no luck

**Comment by unlight** [comment]
It is possible to make compatible types for both sides `ObjectType.User` = `Prisma.User` but for models only.

Other generated graphql types assignable to prisma, for example `UserWhereInput = Prisma.UserWhereInput`
```
    let x: UserWhereInput = {};
    let p: Prisma.UserWhereInput = {};
    p = x; // OK
    // x = p; // Error
    $prisma.user.findMany({ where: x });
```
But assigning `Prisma.UserWhereInput = UserWhereInput` due to union types which support prisma, but graphql does not.
