### ISSUE TITLE
Merge multiple imports

### ISSUE THREAD

**Issue by lodisy** [unlight/prisma-nestjs-graphql#42]
Hello, 

the autogenerated files seem to have seperated imports from the same package, which violets the eslint rule, though it's not a big issue with just _format on save_ to organize imports. But it will be better to be organized by default as unlikely to edit these files.

![Screenshot 2021-08-15 at 21 09 28](https://user-images.githubusercontent.com/8101584/129489769-53959d51-cc9a-45ff-a34d-23ef0b65bf4b.jpg)

![Screenshot 2021-08-15 at 21 15 29](https://user-images.githubusercontent.com/8101584/129489816-f2064017-a27e-4345-a6fe-2d9731c573dc.jpg)

**Comment by unlight** [comment]
It is not possible to take into account all linters, formatters and rules. Just run your custom script after npx prisma generate, e.g.
eslint --fix src/@generated && prettier --write src/@generated
