### ISSUE TITLE
Prisma generate removes custom FieldType imports

### ISSUE THREAD

**Issue by mngu** [unlight/prisma-nestjs-graphql#44]
Hi !

I spotted an issue,
When running `prisma generate`:
- with a custom FieldType,
- and the generated files already exists

=> The custom FieldType is not imported

Example
`schema.prisma`
```javascript
generator nestgraphql {
  ...
  fields_NestGraphQL_from   = "@nestjs/graphql"
  fields_NestGraphQL_input  = true
  fields_NestGraphQL_output = true
}

model User {
  /// @FieldType('NestGraphQL.Int')
  id Int @id @default(autoincrement())
  ...
}
```
The first `prisma generate` is working fine :+1: 
A second `prisma generate` will remove `import * as NestGraphQL from '@nestjs/graphql';` from `user.model.ts`

Can you reproduce this error, or am I doing something wrong ?
Also, is there a way to change a FieldType to one of the built-in `@nestjs/graphql` without doing all the custom imports ?

It would be nice if we could do:
```
/// @FieldType('Int')
```
Then it generates this:
```
@Field(() => Int, {nullable:false})
```

Thanks a lot for your help !

**Comment by unlight** [comment]
@mngu 
Are you using this trick (using Int instead of ID) for all models?

**Comment by mngu** [comment]
Hi @unlight,
Thanks for having a look on this issue.
The solution we found was adding `purgeOutput = true` to our generator options.
Also we switch to `cuid` ids, which is more solid than Int. No need to do this trick anymore !

**Comment by unlight** [comment]
I found that people want to use Int instead of ID, because ID will be serialized to string https://stackoverflow.com/questions/39471075/when-to-use-graphqlid-instead-of-graphqlint Now there is option for this https://github.com/unlight/prisma-nestjs-graphql/tree/next#notypeid
