### ISSUE TITLE
Generate `ArgsTypes` without foreign relations in an input?

### ISSUE THREAD

**Issue by arslancharyev31** [unlight/prisma-nestjs-graphql#47]
Take this generated `ArgsTypes` class as an example.
https://github.com/unlight/prisma-nestjs-graphql/blob/70198db34ad7eb67dc60444f9e747caeb2acb7eb/src/%40generated/tag/create-one-tag.args.ts#L5-L9

Here the `TagCreateInput` type permits creation of `articles`, which may be undesirable. Unfortunately there doesn't seem to be a class generated that would use `TagCreateWithoutArticlesInput` class:
https://github.com/unlight/prisma-nestjs-graphql/blob/70198db34ad7eb67dc60444f9e747caeb2acb7eb/src/%40generated/tag/tag-create-without-articles.input.ts#L3-L10

Would it be possible to add generation of such `ArgsTypes` classes for _Create_ and _Update_ cases respectively?

P.S. Ideally, a class `TagCreateWithoutIdAndArticlesInput` would be generated for such purpose, because it might be undesirable to allow updating of `id` fields.

**Comment by unlight** [comment]
In prisma in `TagCreateArgs` interface `data` property has union type:
```ts
  export type TagCreateArgs = {
    select?: TagSelect | null
    include?: TagInclude | null
    data: XOR<TagCreateInput, TagUncheckedCreateInput>
  }
```
Using option https://github.com/unlight/prisma-nestjs-graphql#useinputtype you can choose generated type
```
generator nestgraphql {
   useInputType_CreateOneTagArgs_data = "TagUncheckedCreateInput"
}
```

Result:
```ts
import { TagUncheckedCreateInput } from './tag-unchecked-create.input';

@ArgsType()
export class CreateOneTagArgs {

    @Field(() => TagUncheckedCreateInput, {nullable:false})
    data!: TagUncheckedCreateInput;
}
```
```ts
@InputType()
export class TagUncheckedCreateInput {

    @Field(() => String, {nullable:true})
    id?: string;

    @Field(() => String, {nullable:false})
    name!: string;
}
```
or more common
```
generator nestgraphql {
   useInputType_CreateOne_data = "matcher:*UncheckedCreateInput"
}
```
Will generate `{Model}UncheckedCreateInput` types for all `data` properties in `{Model}CreateOneXXX` classes.

**Comment by arslancharyev31** [comment]
Using 
```prisma
generator nestgraphql {
  useInputType_CreateOne_data = "matcher:*UncheckedCreateInput"
  useInputType_UpdateOne_data = "matcher:*UncheckedUpdateInput"
}
```
does indeed remove the `articles` property from the input types, which is great. But, the `*UncheckedUpdateInput` types still permit `id` properties, which is undesirable.

Is there any way to get the following result?
```ts
@ArgsType()
export class CreateOneTagArgs {
    @Field(() => TagUncheckedCreateInputWithoutId, {nullable:false})
    data!: TagUncheckedCreateInputWithoutId;
}
```
```ts
@InputType()
export class TagUncheckedCreateInputWithoutId {
    @Field(() => String, {nullable:false})
    name!: string;
}
```

P.S. With this prisma model
```prisma
model Category {
  id       Int       @id @default(autoincrement())
  name     String
  articles Article[] @relation(references: [id], onDelete: Cascade)
}
```
I actually get the following type generated:
```ts
@InputType()
export class CategoryCreateWithoutArticlesInput {
  @Field(() => String, { nullable: false })
  name!: string
}
```
which is great. Problem is, I cannot seem to reference it in the plugin settings. I tried `"matcher:*CreateWithout*Input"`, but it didn't work out.

**Comment by unlight** [comment]
Use https://github.com/unlight/prisma-nestjs-graphql#hidefield
model Category {
  /// @HideField({ match: '*CreateInput' })
  id       Int       @id @default(autoincrement())
  name     String
  articles Article[] @relation(references: [id], onDelete: Cascade)
}

It adds `@HideField()` decorator and removes `id` from schema from all `*CreateInput` types connected with `Category` model.

**Comment by unlight** [comment]
Or just `@HideField({ input: true})`

**Comment by arslancharyev31** [comment]
The following `HideField` directive did the trick:
```prisma
/// @HideField({ match: ['*CreateInput', '*UpdateInput'] })
id       Int       @id @default(autoincrement())
```

Unfortunately the `@HideField({ input: true })` directive ended up producing empty input types like `CategoryWhereUniqueInput`, which raised errors in NestJS.

I sincerely appreciate your help in this issue. Many thanks.
