### ISSUE TITLE
OrderByInput no longer generated

### ISSUE THREAD

**Issue by quinnjr** [unlight/prisma-nestjs-graphql#49]
Prior to the recent version, I was using the generated file for [Type]OrderByInput in my application, such as

```js
import {
  PipelineCreateInput,
  PipelineOrderByInput
} from '../@generated/prisma-graphql/pipeline'
```

However, now PipelineOrderByInput is no longer generated. The same is true for other types defined in my schema.

Environment
---
node: v14.15.4
@nestjs/graphql: v9.0.4
prisma: 3.0.2
prisma-nestjs-graphql: v14.1.0

**Comment by quinnjr** [comment]
Nevermind. This seems to be a change made upstream that I missed.

**Comment by unlight** [comment]
Looks like it was renamed to `OrderByWithRelationInput`

https://github.com/unlight/prisma-nestjs-graphql/issues/46
https://github.com/prisma/e2e-tests/pull/2037/files
