### ISSUE TITLE
Export all classes from one file

### ISSUE THREAD

**Issue by yassinebridi** [unlight/prisma-nestjs-graphql#5]
Currently all the generated classes, have their own files, so the imports can get quite messy pretty quickly, take for example this imported classes:
```ts
import { FindManyTourArgs } from 'prisma/@generated/tour/find-many-tour.args';
import { FindOneTourArgs } from 'prisma/@generated/tour/find-one-tour.args';
import { TourCreateInput } from 'prisma/@generated/tour/tour-create.input';
import { TourWhereUniqueInput } from 'prisma/@generated/tour/tour-where-unique.input';
```
Creating another index.ts file from the `@generated` folder, to export every class would make this a lot cleaner

**Comment by unlight** [comment]
Adding reexport from subfolders is not a big deal, but using generated classes I found that not all of them are necessary for my graphql schema.
`import {FindManyTourArgs} from 'prisma/@generated/tour'` - will cause require and register all inputs, args, enums related to `tour` feature including exotic like `...CreateOrConnectWithout...` and all of them will be added to the graphql schema.

**Comment by yassinebridi** [comment]
That's interesting, typegraphql-prisma is also exporting everything from the generated folder here:

https://github.com/MichalLytek/typegraphql-prisma/tree/main/examples/4-nest-js/prisma/generated/type-graphql

They are probably doing something different for the unused classes to end up in the graphql schema.

**Comment by unlight** [comment]
I suspect that `typegraphql-prisma` should have same issue

**Comment by yassinebridi** [comment]
I will try to produce the issue for the typegraphql-prisma and file an issue there. I will close this issue for now.

**Comment by unlight** [comment]
It could be implemented under option (which is not enabled by default).

**Comment by yassinebridi** [comment]
That would be good option, let the choice to the user.

**Comment by yassinebridi** [comment]
> Adding reexport from subfolders is not a big deal, but using generated classes I found that not all of them are necessary for my graphql schema.
> `import {FindManyTourArgs} from 'prisma/@generated/tour'` - will cause require and register all inputs, args, enums related to `tour` feature, including exotic like `...CreateOrConnectWithout...` and all of them will be added to the graphql schema.

I just noticed that even currently, all of those generated components end up in the graphql schema

**Comment by unlight** [comment]
Depends on schema and how you are using generated classes. 
If you have all models connected by relations and generated classes are used without modification than probably yes - all objects will be added to schema.
