### ISSUE TITLE
Include in FindManyXArgs

### ISSUE THREAD

**Issue by carlosmarioroldan** [unlight/prisma-nestjs-graphql#50]
Hi,

 I was wondering if there's a way to add the **include** argument in the FindManyXArgs.
 
 Something like the one prisma autogenerates
 
 ![image](https://user-images.githubusercontent.com/67707877/133873619-a81ea528-9f3c-4d73-82b9-69bfa51c110a.png)

Currenty this is what it generates

```ts
@ArgsType()
export class FindManyUserArgs {
    @Field(() => UserWhereInput, {nullable:true})
    where?: UserWhereInput;

    @Field(() => [UserOrderByWithRelationInput], {nullable:true})
    orderBy?: Array<UserOrderByWithRelationInput>;

    @Field(() => UserWhereUniqueInput, {nullable:true})
    cursor?: UserWhereUniqueInput;

    @Field(() => Int, {nullable:true})
    take?: number;

    @Field(() => Int, {nullable:true})
    skip?: number;

    @Field(() => [UserScalarFieldEnum], {nullable:true})
    distinct?: Array<keyof typeof UserScalarFieldEnum>;
}
```

I'd need something like this

```ts
@ArgsType()
export class FindManyUserArgs {
    ...
    
   @Field(() => UserIncludeInput, { nullable: true })
   include?: UserIncludeInput;
}
```

The reason is because I need to run queries like this

![image](https://user-images.githubusercontent.com/67707877/133873757-77b5251d-fe4c-4a19-b109-c4d75f6381a0.png)

Thanks in advance!

**Comment by unlight** [comment]
Take a look at Prisma Select plugin https://paljs.com/plugins/select/

**Comment by carlosmarioroldan** [comment]
@unlight thank you for your help. Unfortunately the company where I work won't allow me to add this dependency to the project. Is there a way to tell the generator to add the include field in the FindManyUserArgs so I can include relations from the client?

Regards

**Comment by unlight** [comment]
There is no options for such case.
But I think 'select' is more suitable this case. You can reinvent the wheel and create your own fields parser, like https://github.com/Robert-W/graphql-outfields and use result in 'select' propert of 'findMany' method.

**Comment by carlosmarioroldan** [comment]
Thank you very much for all your help

**Comment by carlosmarioroldan** [comment]
@unlight Sorry for reopening this issue. I just think it would be awesome if we could generate the include **InputType**

Something like this

![image](https://user-images.githubusercontent.com/67707877/135674206-e03ca839-42d8-400f-9f08-b111a5398119.png)

This would give us the possibility to fully handle the query from the client

![image](https://user-images.githubusercontent.com/67707877/135674343-1cd3c080-c994-4e6b-ac65-307c7f87e760.png)

The playground

![image](https://user-images.githubusercontent.com/67707877/135674934-627ad108-45c4-4fe1-b913-ed55cc3e75c5.png)

Thanks!

**Comment by unlight** [comment]
I think this is wrong decision to use `include`.

Image table with 100+ columns, using `include` will select all 100+ fields, despite client requested only single. It's best practice only return the data you need https://docs.oracle.com/middleware/1221/bip/BIPDM/best_practices.htm#BIPDM534

It's by design of graphql that select fields is not part of args.

**Comment by carlosmarioroldan** [comment]
I'm not sure if I understand correctly. I'm aiming for fetching only the data I need but with an slight modification.

Instead of telling prisma to include the relations in the service

```ts
async getUsers(): Promise<User[]> {
  this.prisma.user.findMany({   
    include: {
      posts: true,
    },
  });
}
```

I'd pass the includes and data I need from the arguments in the query

```ts
async getUsers({ include }: FindManyUserArgs): Promise<User[]> {
  this.prisma.user.findMany({   
    include
  });
}
```

```graphql
query getUsers {
  users(include: {
    posts: true
  }) {
    id,
    name,
    posts: {
      name
    }
  }
}
```

**Comment by carlosmarioroldan** [comment]
@unlight Oh I didn't know that. Thank you so much for this piece of information.

**Comment by hotrungnhan** [comment]
> The problem is that `this.prisma.user.findMany({ include { posts: true } })` selects ALL columns from posts table, but graphql server will send to client only `name`. You should use `select`
> 
> ```
> this.prisma.user.findMany({ select: { id: true, name: true, posts: { select: { name: true }} } })
> ```
> 
> `{ select: { id: true, name: true, posts: { select: { name: true }} } }` this object can be created from `GraphQLResolveInfo`
> 
> ```ts
>     @Query(() => [User])
>     async users(
> 		@Args() args: FindManyUserArgs,
>         @Info() info: GraphQLResolveInfo,
>     ) {
>         const select = createUserSelectFromInfo(info);
>         return await prisma.user.findMany({ ...args, select });
>     }
> ```
> 
> See https://docs.nestjs.com/graphql/resolvers#graphql-argument-decorators

 why didn't put a doccument on this ?

**Comment by Songkeys** [comment]
How do I type the `args` in `FindManyUserArgs` or `FindUniqueUserArgs`?

Here is an example query from https://paljs.com/plugins/select#example-query :

```gql
query {
  findUniqueUser(where: { id: 1 }) {
    id
    email
    name
    posts(where: { title: { contains: "a" } }, orderBy: { createdAt: asc }, first: 10, skip: 5) {
      id
      title
      comments(where: { contain: { contains: "a" } }) {
        id
        contain
      }
    }
  }
}
```

which maps to the prisma query:

```js
const result = {
  select: {
    id: true,
    email: true,
    name: true,
    posts: {
      select: {
        id: true,
        title: true,
        comments: {
          select: { id: true, contain: true },
          where: { contain: { contains: 'a' } },
        },
      },
      where: { title: { contains: 'a' } },
      orderBy: { createdAt: 'asc' },
      first: 10,
      skip: 5,
    },
  },
};
```

But the `FindManyUserArgs` or `FindUniqueUserArgs` or `GraphQLResolveInfo` do not have the nested query typing like `select.where`. How could I fix this?
