### ISSUE TITLE
Generate (export) all object (classes) types into one file

### ISSUE THREAD

**Issue by jakubvanco** [unlight/prisma-nestjs-graphql#6]
At this time, I have all object types divided to folders by entity and I would need to have one big file with all of these exports.

Thanks in advance.

**Comment by yassinebridi** [comment]
Set the `reExportAll` option to true, it is already in the documentation.

**Comment by jakubvanco** [comment]
Yes, that’s true, but I need just one big file with all exports.

**Comment by unlight** [comment]
@jakubvanco 

What version do you use?
It's already should work since version 7.1

**Comment by jakubvanco** [comment]
In 7.1 and newer versions is an option to reExportAll = true; which results in following folder structure:

OurEntity
- aggregate-ourEntity.args.ts
- ourEntity.model.ts
- … others
- index.ts (that reexports everything from files above); 
….OtherEntites
index.ts <— that reexports from indexes;

But if we integrate your solution with monorepo (Nx.Dev) there is a default setting which forbids cyclic dependency between files. So OurEntity.model cannot have a field from our Other entity if there is a backward reference. We can turn that setting off for now, but it would be great if you can generate all classes into single index.ts, that will resolve the issue with this cycle dependency constraint.

**Comment by unlight** [comment]
So, let's clarify:
```
@generated/user/index.ts
@generated/post/index.ts
@generated/index.ts
```

You want only `@generated/index.ts` without feaure index files (`@generated/{user,post}/index.ts`), correct?

**Comment by jakubvanco** [comment]
Exactly, one @generated/index.ts file with all classes.

**Comment by yassinebridi** [comment]
@unlight I'm not sure if the latest release closes this issue.

As i understand this would generate a single file with all the classes like prisma does in their client.
I tried the latest release with new `reExport` option, i think the `Single` enum is intended to be used for this functionality.

But the `Single` option just re-export the the files from other folders.

**Comment by unlight** [comment]
I misunderstood it.
We are talking about bundling, not re-export.
New issue is created #15
