### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by sgentile** [unlight/prisma-nestjs-graphql#63]
I like what I'm seeing - I'm curious - I need to be able to add attributes for federation support

ie sample schema:

```
type Post @key(fields: "id") {
  id: ID!
  title: String!
  content: String!
  published: Boolean!
  createdAt: String!
  userId: Int
  user: User
}


extend type Query {
  posts: [Post!]!
  post(id: ID!): Post
}

extend type User @key(fields: "id") {
  id: ID! @external
  posts: [Post]
}
```

Is this possible ?

**Comment by unlight** [comment]
@sgentile 
Could you describe your case?
I added manually keys, extend, external directives, but nothing is changed in schema.
Are you using several prisma schemas, own schema for each seevice?
