### ISSUE TITLE
Add option to disable alphabet order of the field names of the generated schema

### ISSUE THREAD

**Issue by lodisy** [unlight/prisma-nestjs-graphql#68]
![Screenshot 2021-11-03 at 20 45 29](https://user-images.githubusercontent.com/8101584/140181751-de2add7c-8ab3-4404-9960-7f7857617cd4.jpg)

Can we add an option to disable this? Just follow the field order of the models defined in prisma's schema file.

**Comment by unlight** [comment]
Properties intentionally are not sorted. The order is same as in prisma types.

**Comment by lodisy** [comment]
> Properties intentionally are not sorted. The order is same as in prisma types.

Thanks for your reply. 

Sorry this was caused by @nestjs/graphql `sortSchema` config...
