### ISSUE TITLE
Error: EMFILE: too many open files

### ISSUE THREAD

**Issue by omar-dulaimi** [unlight/prisma-nestjs-graphql#69]
Hello,

I keep running into this error:

`Error: EMFILE: too many open files,`

everytime I run generate.

I tried to increase these system config values:

```
fs.inotify.max_user_watches = 999524288
fs.inotify.max_user_instances = 1024
```

and also included the generated folder path inside vsCode user settings exclude file watchers. But still no luck.

I use Ubuntu 18.04

**Comment by unlight** [comment]
Please, provide more context, stack trace, schema or steps how to reproduce it

**Comment by omar-dulaimi** [comment]
Unfortunately I cannot provide the schema. But what's worth noting about it is that it's a big one. I managed to solve the issue after a lot of digging around.

It only happens on unix systems. On windows it works fine.

So not sure if there's anything to improve on the library side. Maybe a hint when this error occurs that we should change some values in our OS or something. Other than that, feel free to close the ticket.
