### ISSUE TITLE
Purging for a new generation

### ISSUE THREAD

**Issue by yassinebridi** [unlight/prisma-nestjs-graphql#7]
Currently whenever you regenerate, new classes adds in, while old ones stay there, which creates a conflict, so you have to manually remove the generated folder every time.
It would be neat to have a mechanism in place that auto purges the generated folder before each regenertaion.

**Comment by unlight** [comment]
Are you talking about generation in watch mode or run once? If last, then just use rm - rf @generated/folder.

**Comment by yassinebridi** [comment]
About the last, since prisma purge the prisma client too, i thought it might be cool to do the same.

**Comment by unlight** [comment]
Prisma client generates single file, prisma-nestjs-graphql generates multiple files.
It's simpler to delete folder before generation.

**Comment by yassinebridi** [comment]
Yeah that makes sense.

**Comment by unlight** [comment]
I would like to keep this open. Maybe some improvements related to will be done some day.

**Comment by unlight** [comment]
Since generator initially designed for as well as update existing source code using different target folders, ability to delete files in output folder will be under configuration option, disabled by default.

**Comment by unlight** [comment]
Will be released on default in several days.
