### ISSUE TITLE
Error: Excessive stack depth comparing types 

### ISSUE THREAD

**Issue by jasonmacdonald** [unlight/prisma-nestjs-graphql#75]
I seem to be getting this issue whenever I try to call something using these Inputs or Args.

`Excessive stack depth comparing types '{ data: CompanyCreateInput; }' and 'CompanyCreateArgs'.ts(2321)`

It seems to get stuck in some kind of recursion where one eventually references the other. But this plugin generates so many class files I cannot tell which one is the culprit or if there's anything I can do to stop it. Any suggestions?

**Comment by unlight** [comment]
Check #65

**Comment by jasonmacdonald** [comment]
After spending an entire day trying to debug this, it turns out the problem is the default TS version in VSCode. By telling VScode to use the project TS version the error went away. Such a pain.

**Comment by unlight** [comment]
This issue can popup in latest or future versions, see solution in this comment https://github.com/unlight/prisma-nestjs-graphql/issues/65#issuecomment-994742228
