### ISSUE TITLE
Question: How to properly resolve _count on entities with a lot of references?

### ISSUE THREAD

**Issue by jasonmacdonald** [unlight/prisma-nestjs-graphql#76]
I'm trying to figure out if there is a proper way to handle this in a resolver. I have a table (account) that almost every other table refers to. When using the Graphql sandbox you can ask the account query to return `_count: { ....refs }`. 

example query:
```graphql
query {
  accounts {
    _count {
      table1
      table2
      table3
      table4
      table5
      table6
      table7
      table8
      table9
    }
  }
}
```

Is the intention that you have a single `@resolveField` for `_count` and query every single table aggregate for its count? This seems like a very inefficient thing to do.

Is there a better way to resolve this? I can't seem to find any info about it. 

My preference might be to just hide this field altogether from the Graphql Schema, but since this isn't a Prisma database field, I'm not sure how I can hide it from the generated classes.

**Comment by unlight** [comment]
Generated classes corresponds to prisma types.

To return aggregate (e.g.AggregateArticle) it must queried like this
```
prisma.article.groupBy({
    _count: {
        // ...
     },
});
```
I don't know what query will be generated under the hood. I'll check.

So, you want to hide `_count` in `ArticleAggregateArgs ` class?
https://github.com/unlight/prisma-nestjs-graphql/blob/master/@generated/article/article-aggregate.args.ts#L33

**Comment by jasonmacdonald** [comment]
Yes, basically if you have a lot of relations, it lumps them all under `_count` using the `AccountCount` class. In that class is a property for each model that references `Account.id` as a foreign key constraint (which is everything if you use it as a customer discriminator). This means either I have to implement all those aggregate calls under the field resolver `_count` or I need to hide it from the Graphql generated schema because right now it shows when developers use the Sandbox to build a query. 

Something like this:

```graphql
query {
  accounts {
    _count {
     // pretend these are actual models
      model1
      model2
      model3
      model4
      model5
      model6
      model7
      model8
      model9
    }
  }
}
```
This was created with a few clicks in the sandbox, but I can't figure out how to implement it properly. Either I need to hide it, or I need a better way to avoid doing something like this on the example I gave. 

```typescript
export class AccountResolver {
  // Query & Mutations cut
  ...

   @ResolveField('_count', () => AccountCount)
   async _count(@Parent() { id }) {
    
        input._count = { _all: true };
        
        return {
              model1: Prisma.model1.findAggregate(input),
              model2: Prisma.model2.findAggregate(input),
              model3: Prisma.model3.findAggregate(input),
              model4: Prisma.model4.findAggregate(input),
              model5: Prisma.model5.findAggregate(input),
              model6: Prisma.model6.findAggregate(input),
              model7: Prisma.model7.findAggregate(input),
              ...
              // Depending on the number of references it could be every table in the DB 
              // assuming Account is used to segregate customers 
       }
    }
}

```
**I know this code isn't 100% accurate or runnable, I'm just trying to illustrate the issue quickly**

 In order to resolve the `_count` field on a model with a lot of foreign key references to it, you end up with something akin to this. Worse, actually, because I generally don't want to call Prisma directly like this example but instead use the other modules' services.

Perhaps I'm totalling missing a better way than this, but to me, this is just something I would rather not let people do.

**Comment by unlight** [comment]
You do not need to implement `@ResolveField('_count', () => AccountCount)` function,
`_count` data can be queried right here.
```ts
    @Query(() => User, { nullable: true })
    async userInfo(@Args('user') where: UserWhereUniqueInput): Promise<User | null> {
        const user = await prisma.user.findUnique({
            where,
            include: {
                _count: {
                    select: { followers: true },
                },
            },
        });
		/**
	  user {
	  id: 'ckxaqyfkk0000w4upbykbte0e',
	  email: 'joe@mail.com',
	  name: 'Joe',
	  password: '123',
	  bio: null,
	  image: null,
	  countComments: null,
	  rating: null,
	  role: null,
		  _count: { followers: 1 }
	  }
	**/
        return user;
    }
```
Following query will work without any `@ResolveField('_count)` decorator.
```graphql
query {
  userInfo(where: { name: "Joe" }) {
    id
    _count {
      followers
    }
  }
}
```
Of course it example, and client can request other counts, e.g.
```
query {
  userInfo(where: { name: "Joe" }) {
    id
    _count {
      favoriteArticles
      following
      followers
      articles
      comments
    }
  }
}
```
For all possible counts query will be:
```ts
    const user = await prisma.user.findUnique({
        where,
        include: {
            _count: true
        },
    });
```
Which generates:

<details>
<summary>Details</summary>
```sql
EXPLAIN SELECT "public"."User"."id",
	"aggr_selection_0_User"."_aggr_count_following",
	"aggr_selection_1_User"."_aggr_count_followers",
	"aggr_selection_2_Article"."_aggr_count_favoriteArticles",
	"aggr_selection_3_Article"."_aggr_count_articles",
	"aggr_selection_4_Comment"."_aggr_count_comments"
FROM "public"."User"
LEFT JOIN (
	SELECT "public"."User"."id",
		COUNT(("public"."_UserFollows"."B")) AS "_aggr_count_following"
	FROM "public"."User"
	LEFT JOIN "public"."_UserFollows" ON ("public"."User"."id" = ("public"."_UserFollows"."B"))
	GROUP BY "public"."User"."id"
	) AS "aggr_selection_0_User" ON ("public"."User"."id" = "aggr_selection_0_User"."id")
LEFT JOIN (
	SELECT "public"."User"."id",
		COUNT(("public"."_UserFollows"."A")) AS "_aggr_count_followers"
	FROM "public"."User"
	LEFT JOIN "public"."_UserFollows" ON ("public"."User"."id" = ("public"."_UserFollows"."A"))
	GROUP BY "public"."User"."id"
	) AS "aggr_selection_1_User" ON ("public"."User"."id" = "aggr_selection_1_User"."id")
LEFT JOIN (
	SELECT "public"."User"."id",
		COUNT(("public"."_FavoritedArticles"."B")) AS "_aggr_count_favoriteArticles"
	FROM "public"."User"
	LEFT JOIN "public"."_FavoritedArticles" ON ("public"."User"."id" = ("public"."_FavoritedArticles"."B"))
	GROUP BY "public"."User"."id"
	) AS "aggr_selection_2_Article" ON ("public"."User"."id" = "aggr_selection_2_Article"."id")
LEFT JOIN (
	SELECT "public"."Article"."authorId",
		COUNT(*) AS "_aggr_count_articles"
	FROM "public"."Article"
	GROUP BY "public"."Article"."authorId"
	) AS "aggr_selection_3_Article" ON ("public"."User"."id" = "aggr_selection_3_Article"."authorId")
LEFT JOIN (
	SELECT "public"."Comment"."authorId",
		COUNT(*) AS "_aggr_count_comments"
	FROM "public"."Comment"
	GROUP BY "public"."Comment"."authorId"
	) AS "aggr_selection_4_Comment" ON ("public"."User"."id" = "aggr_selection_4_Comment"."authorId")
WHERE "public"."User"."name" = 'Joe'
```
</details>

If you consider this as overkill, then there is a plugin "prisma select" https://github.com/paljs/prisma-tools/tree/main/packages/plugins which can map requested graphql fields to prisma select object.

In general, graphql performance (client may request huge amount of data) is one of the disadvantage of graphql.
Usual solution for this is limit query complexity for clients, see https://docs.nestjs.com/graphql/complexity for more details.

**Comment by unlight** [comment]
Currently, it is not possible to hide `_count` in `UserCount` class.

**Comment by jasonmacdonald** [comment]
Thanks for the help, @unlight! I knew I was missing something and it seems it's the "include". Although, that property doesn't seem to exist on the generated Graphql inputs, only the Prisma ones. Is that intentional?

**Comment by jasonmacdonald** [comment]
I see now that the select plugin solves all my problems. Thanks again!

**Comment by unlight** [comment]
Selecting `_count` through `select` will also work.
```
        const user = await prisma.user.findUnique({
            where,
            select: {
                id: true,
                _count: true,
            },
        });
```

This is related issue about `include` https://github.com/unlight/prisma-nestjs-graphql/issues/50

**Comment by unlight** [comment]
Selecting `_count` through `select` will also work.
```
        const user = await prisma.user.findUnique({
            where,
            select: {
                id: true,
                _count: true,
            },
        });
```
> Although, that property doesn't seem to exist on the generated Graphql inputs, only the Prisma ones. Is that intentional?

Yes, prisma types and graphql types are not same, because of some design constraints (e.g. graphql does not have input union types)

This is related issue about `include` https://github.com/unlight/prisma-nestjs-graphql/issues/50
