### ISSUE TITLE
Add StringFilter | string type in WhereInput

### ISSUE THREAD

**Issue by rnkhouse** [unlight/prisma-nestjs-graphql#78]
File create by `prisma-nestjs-graphql`:

    @InputType()
    export class business_usersWhereInput {
        @Field(() => [business_usersWhereInput], {nullable:true})
        AND?: Array<business_usersWhereInput>;
        @Field(() => [business_usersWhereInput], {nullable:true})
        OR?: Array<business_usersWhereInput>;
        @Field(() => [business_usersWhereInput], {nullable:true})
        NOT?: Array<business_usersWhereInput>;
        @Field(() => IntFilter, {nullable:true})
        id?: IntFilter;
        @Field(() => IntFilter, {nullable:true})
        business_id?: IntFilter;
        @Field(() => StringFilter, {nullable:true})
        email?: StringFilter;
        @Field(() => StringFilter, {nullable:true})
        password?: StringFilter;
        @Field(() => StringFilter, {nullable:true})
        first_name?: StringFilter;
        @Field(() => StringFilter, {nullable:true})
        last_name?: StringFilter;
    }

For the same table, file created by `prisma-client-js`:

    export type business_usersWhereInput = {
        AND?: Enumerable<business_usersWhereInput>
        OR?: Enumerable<business_usersWhereInput>
        NOT?: Enumerable<business_usersWhereInput>
        id?: IntFilter | number
        business_id?: IntFilter | number
        email?: StringFilter | string
        password?: StringFilter | string
        first_name?: StringFilter | string
        last_name?: StringFilter | string
    }

How can I add 2 types (StringFilter | string) in the file generated by `prisma-nestjs-graphql`?

**Comment by unlight** [comment]
You cant. Graphql input union type is not yet described in specification, and thus not supported by Nest?

**Comment by rnkhouse** [comment]
@unlight  Thanks for the quick response. Is there any future plan to implement this feature? Also, please let me know if there is any way to convert between types. `StringFilter => string` and viseversa.

**Comment by unlight** [comment]
> Is there any future plan to implement this feature?
It is the question for graphql foundation, they are discussing it around 5 five years https://github.com/graphql/graphql-spec/issues/488, then it must be implemented in nestjs.

You cannot take both graphql types, but you can choose between them, see https://github.com/unlight/prisma-nestjs-graphql#useinputtype

Example:
```
generator nestjsgraphql {
	useInputType_WhereInput_id = "match:Int"
	useInputType_WhereInput_email = "match:String
```
May generate:

```ts

    @Field(() => Int, {nullable:true})
    id?: number;

    @Field(() => String, {nullable:true})
    email?: string;
```
