### ISSUE TITLE
Ignore field generation

### ISSUE THREAD

**Issue by stevefan1999-personal** [unlight/prisma-nestjs-graphql#8]
Hi I want to ignore my password field from generating first, so that I don't have to copy it to my own source set and merge the generated files one by one (I set gitignore on the generated files).

In typegraphql-prisma, you can do this by setting omit:
```prisma
  /// @TypeGraphQL.omit(output: true)
  password  String
```
I think it is not that hard to implement 😂

**Comment by unlight** [comment]
> so that I don't have to copy it to my own source set and merge the generated files one by one

There is a more easier way:
```ts
// src/user/models/user.model.ts (copied from generated)
import { Field, HideField, ID, ObjectType } from '@nestjs/graphql';

@ObjectType({})
export class User {
    @Field(() => String, {
        nullable: false,
    })
    name!: string;

    @HideField()
    password!: string;
}
```

```ts
// @generated/user/user.model.ts
export { User } from '../../user/models/user.model';
```

Generator will generate class but comment it, if export with same model name found.

But I agree, need somehow to automate this.

**Comment by unlight** [comment]
```
/// @TypeGraphQL.omit(output: true)
```
Is this real usage in TypeGraphQL?

Triple slash is used for documentation, for comments need to use double slash.

**Comment by stevefan1999-personal** [comment]
> ```
> /// @TypeGraphQL.omit(output: true)
> ```
> Is this real usage in TypeGraphQL?
> 
> Triple slash is used for documentation, for comments need to use double slash.
> 
> 

*prisma, it's an ast attached comment like decorator

**Comment by unlight** [comment]
@stevefan1999-personal 
Do you need to remove password from input types also?
