### ISSUE TITLE
Is it possibl to hide certain operations on nested types?

### ISSUE THREAD

**Issue by corynorris** [unlight/prisma-nestjs-graphql#80]
For example if we have:

@InputType()
```
export class ArticleCreateNestedManyWithoutAuthorInput {
    @Field(() => [ArticleCreateWithoutAuthorInput], { nullable: true })
    create?: Array<ArticleCreateWithoutAuthorInput>;

    @Field(() => [ArticleCreateOrConnectWithoutAuthorInput], { nullable: true })
    connectOrCreate?: Array<ArticleCreateOrConnectWithoutAuthorInput>;

    @Field(() => ArticleCreateManyAuthorInputEnvelope, { nullable: true })
    createMany?: ArticleCreateManyAuthorInputEnvelope;

    @Field(() => [ArticleWhereUniqueInput], { nullable: true })
    connect?: Array<ArticleWhereUniqueInput>;
}

```
And only wanted to show the operation
```
@InputType()
export class ArticleCreateNestedManyWithoutAuthorInput {
    @Field(() => [ArticleWhereUniqueInput], { nullable: true })
    connect?: Array<ArticleWhereUniqueInput>;
}
```

I can't seem to find an operation in `useInputType_UserCreateNestedOneWithoutCardInput` to remove types, and following another post adding a custom `HideField` doesn't seem to have an impact since it doesn't remove the existing `Field` decorator

Is this possible or should I just hide the entire relationship / create a custom input type?

**Comment by unlight** [comment]
Yes, it is possible, but it a little bit verbose.
Use https://github.com/unlight/prisma-nestjs-graphql#decorate config option
```
generator nestgraphql {
    decorate_1_type = "PostCreateNestedManyWithoutAuthorInput" // outmatch pattern can be used
    decorate_1_field = "!(connect)" // outmatch pattern
    decorate_1_name = HideField
    decorate_1_from = "@nestjs/graphql"
    decorate_1_arguments = "[]"
}
```
It will add `@HideField()` decorator for all except `connect` property, properties should be removed from GraphQL schema, but not from typescript class.

> Is this possible or should I just hide the entire relationship / create a custom input type?
It's your call.
For my POV it does not make sense to have class with just single property only.
(I recall about some eslint-plugin which have such rule)

**Comment by corynorris** [comment]
Thanks for your response!

I actually did try this but the issue was it adds the `HideField()` as folllows
```
export class ArticleCreateNestedManyWithoutAuthorInput {
    @Field(() => [ArticleCreateWithoutAuthorInput], { nullable: true })]
    @HideField()
    create?: Array<ArticleCreateWithoutAuthorInput>;

    @Field(() => [ArticleCreateOrConnectWithoutAuthorInput], { nullable: true })
    @HideField()
    connectOrCreate?: Array<ArticleCreateOrConnectWithoutAuthorInput>;

    @Field(() => ArticleCreateManyAuthorInputEnvelope, { nullable: true })
    @HideField()
    createMany?: ArticleCreateManyAuthorInputEnvelope;

    @Field(() => [ArticleWhereUniqueInput], { nullable: true })
    connect?: Array<ArticleWhereUniqueInput>;
}
```

And unfortunately since there is now both a `Field()` and a `HideField()` it still shows up in the GraphQL schema.

But to your other point, I guess the better approach would be to hide the relationship from the create/update mutations via something like:

```
model Article {
  /// @HideField({ match: 'Article@(Create|Update)*Input' })`, and then to 
  author         User      @relation(name: "ArticleAuthor", fields: [authorId], references: [id])
  authorId       String
}

```
And then just do the logic in the resolver/service ~ 
```
  @Mutation(() => Article)
  createArticle(@Args() article: CreateArticleInput, @Args() author: UserWhereUniqueInput) {
      await prisma.user.create({
          data: {
              ...article,
              author: {
                  connect: [author],
              },
          }
      })
  }
```

**Comment by unlight** [comment]
Oh, I see. Both `@HideField()` does not work with `@Field`.

**Comment by magrinj** [comment]
@unlight Thanks for this great project !
Is there any plan to fix this issue ?

**Comment by unlight** [comment]
@magrinj
This feature requires a lot of effort (a lot of changes need to be made) I dont know when I can find time for this.

**Comment by Unit2795** [comment]
I've run into a similar issue and created a temp fix.

I have some fields, such as a user's password hash which is easy enough to hide with `/// @HideField()` but it still shows up in `where` and `orderBy` in other models that have a relation with the users model. I don't want people to know this field even exists.

I used a regular expression like this: `/\n\n.*@Field.*\n.*hash.*/g` and used a [post](https://docs.npmjs.com/cli/v8/using-npm/scripts#pre--post-scripts) npm script after running `prisma generate` to remove the unwanted fields. I can provide the script if anyone wants it. If you have a better solution I'd love to hear about it.

Thank you for making such a handy tool!
