### ISSUE TITLE
_count field in graphql main model always generate nullable:false

### ISSUE THREAD

**Issue by cobianwae** [unlight/prisma-nestjs-graphql#84]
Hi i sincerely thank you for your work :)

I don't know if i did something wrong or it was a bug. The lib always generate _count field as nullable flase. Following is the code generated

`@Field(() => [UsersOnRoles], {nullable:true})
    roles?: Array<UsersOnRoles>;

    @Field(() => UserCount, {nullable:false})
    _count?: UserCount;`

Thanks again. This is my first time ever posting any issue on open source code ;p

**Comment by unlight** [comment]
Are getting error when returning UserModel from resolver, something like _count cannot be null?

Or the issue in TypeScript property type with qustion mark `?`

**Comment by cobianwae** [comment]
Later i found out if i omitted the field from client side it's fine. But if i included the field and didn't properly set the value it will throw error as required field. i expected it to be nullable with question mark ?. But i think it is minor. I will just exclude it. It was included automatically using graphql generator, that's why.

Thanks for amazing works bro :)

**Comment by unlight** [comment]
If nullable in graphql meaning then it is Field decorator options
```
    @Field(() => UserCount, { nullable: true })
    _count?: UserCount;
```
In prisma this field marked as non-nullable.

It is not possible to make typescript type nullable (question mark `?`) because it will break type compatibility between Prisma and GraphQL models.

**Comment by Johann01** [comment]
Is there a way to say it is always nullable:true ?

**Comment by denes16** [comment]
How can i delete this field?, since this field its not in the type definition on the prisma client type as a part of the model.
