### ISSUE TITLE
Why big-int-filter.input.ts @Field data type is String?

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [unlight/prisma-nestjs-graphql#87]
How can change String to GraphQLBigInt scalar type?
![image](https://user-images.githubusercontent.com/45883300/156993618-a1425a6e-6500-4689-809f-8d11cab8f458.png)

**Comment by unlight** [comment]
Oh, sorry, it will not change field type in `big-int-filter.input.ts`

**Comment by Abdulrahmanelheyb** [comment]
Yes I use GraphQLBigInt from graphql-scalars

> Currently it is not possible, are going to use GraphQLBigInt from `graphql-scalars`?

**Comment by Abdulrahmanelheyb** [comment]
I think changing manually but when generate again is be lost.

**Comment by unlight** [comment]
I thought about to add support of bigint as GraphQLBigInt from `graphql-scalars`, but it does not support input as string and output as number which lead to data loss https://github.com/Urigo/graphql-scalars/issues/1496

I think I will make a config options to left decision up to the user

**Comment by unlight** [comment]
https://github.com/unlight/prisma-nestjs-graphql#graphqlscalars
