### ISSUE TITLE
`tsConfigFilePath` is ignored

### ISSUE THREAD

**Issue by roziscoding** [unlight/prisma-nestjs-graphql#88]
When using `emitCompiled`, the `tsConfigFilePath` option [is ignored](https://github.com/unlight/prisma-nestjs-graphql/blob/master/src/helpers/create-config.ts#L103) which leads to TypeScript using different options than what I need for my project.
Is it possible to allow for this configuration to be passed on to the TypeScript compiler so it generates code compatible with my application code?

**Comment by unlight** [comment]
It does not ignored. Some options will be disabled like emitDecoratorMetadata, due to TDZ issue.

What options from your config are not applies?

**Comment by roziscoding** [comment]
Actually no configuration from my tsconfig seems to be applied, but I'm looking at the `target` property. The emitted files are using a target before ES2015, which causes them to use functions instead of ES2015 classes.

I can't see how the file path is not ignored, tho, since the `createConfig` function always returns its value as `undefined` 🤔

**Comment by unlight** [comment]
Yes, you are correct. I was looking into wriong way.
I'll fix that.

**Comment by roziscoding** [comment]
thank you!
let me know if you need any help with mantaining this project. I really like it :)
