### ISSUE TITLE
@PropertyType({ name: 'Prisma.Decimal', from: '@prisma/client', namedImport: true }) Are set Prisma.Decimal all inputs target field!

### ISSUE THREAD

**Issue by Abdulrahmanelheyb** [unlight/prisma-nestjs-graphql#91]
When I give the `@PropertyType({ name: 'Prisma.Decimal', from: '@prisma/client', namedImport: true })` decarator, it is set to Prisma.Decimal in all input fields, but because of this, most of the arguments have an error. Example:

`src/order-detail/order-detail.resolver.ts:33:42 - error TS2345: Argument of type 'OrderDetailAggregateArgs' is not assignable to parameter of type '{ where?: OrderDetailWhereInput; orderBy?: Enumerable<OrderDetailOrderByWithRelationInput>; cursor?: OrderDetailWhereUniqueInput; ... 6 more ...; _max?: OrderDetailMaxAggregateInputType; }'.
  Types of property 'orderBy' are incompatible.
    Type 'OrderDetailOrderByWithRelationInput[]' is not assignable to type 'Enumerable<OrderDetailOrderByWithRelationInput>'.
      Type 'import("src/@generated/order-detail/order-detail-order-by-with-relation.input").OrderDetailOrderByWithRelationInput[]' is not assignable to type 'import("node_modules/.prisma/client/index").Prisma.OrderDetailOrderByWithRelationInput[]'.
        Type 'import("src/@generated/order-detail/order-detail-order-by-with-relation.input").OrderDetailOrderByWithRelationInput' is not assignable to type 'import("node_modules/.prisma/client/index").Prisma.OrderDetailOrderByWithRelationInput'.
          The types of 'order.price' are incompatible between these types.
            Type 'Decimal' is not assignable to type 'SortOrder'.
`
How can solve this? 😟

**Comment by unlight** [comment]
I was thinking, why do we need custom type for decimal. It's built in to prisma... I think this issue can be considered as bug, decimal field should be mapped to Prisma.Decimal instead of any.

**Comment by Abdulrahmanelheyb** [comment]
> I was thinking, why do we need custom type for decimal. It's built in to prisma... I think this issue can be considered as bug, decimal field should be mapped to Prisma.Decimal instead of any.

Yes, because `///@PropertyType({ name: 'Prisma.Decimal', from: '@prisma/client', nameImport: true })' not only modifies the input or output, it is all generated files are also set, Most of the error in the first comment look at the last line there it added Decimal instead of SortFoo

**Comment by Abdulrahmanelheyb** [comment]
> Sorry, it's not clear what's error about. But looks like you can not apply `@PropertyType` to all inputs, use `match` in parameters, e.g
> 
> ```
> /// @PropertyType({ name: 'Prisma.Decimal', from: '@prisma/client', namedImport: true, match: '*CreateInput' })
> ```
> 
> It will change type only for `***CreateInput` classes.
> 
> See https://github.com/axtgr/outmatch#readme for details how `match` works.

Thanks I fixed error when I give `output: true`
`
/// @PropertyType({ name: 'Prisma.Decimal', from: '@prisma/client', namedImport: true, output: true })
`
